// Stage 2 route guide batch 1 — authored entries for 20 Scotland-origin routes.
// NOT imported into MOVING_ROUTE_PAGES. Routes here return genuine 404s in production
// because the route page uses dynamicParams = false and generateStaticParams only
// reads MOVING_ROUTE_PAGES. Import into MOVING_ROUTE_PAGES only after the Stage 1
// review gate is cleared (production deployment + GSC indexing confirmed).
import type { MovingRoutePage } from "./moving-route-pages";

const sources = {
  scottishLez: { label: "Scottish Government: low emission zones", href: "https://www.mygov.scot/low-emission-zones" },
  edinburgh: { label: "Edinburgh Council: dispensations and suspensions", href: "https://www.edinburgh.gov.uk/parking-spaces/dispensations-suspensions" },
  london: { label: "Transport for London: loading on red routes", href: "https://tfl.gov.uk/modes/driving/red-routes/rules-of-red-routes/loading-for-the-public" },
  manchester: { label: "Manchester City Council: loading bays", href: "https://www.manchester.gov.uk/parking/tickets-and-fines/parking-restrictions/parking-restrictions/parking-in-a-loading-bay" },
  birmingham: { label: "Transport for West Midlands: Birmingham Clean Air Zone", href: "https://www.tfwm.org.uk/plan-your-journey/ways-to-travel/driving-in-the-west-midlands/birmingham-clean-air-zone/" },
  bristol: { label: "Bristol City Council: Clean Air Zone vehicle checker", href: "https://www.bristol.gov.uk/residents/streets-travel/bristols-caz/charges-and-vehicle-checker" },
  newcastle: { label: "Newcastle City Council: parking dispensations", href: "https://new.newcastle.gov.uk/parking/dispensations-and-suspensions" },
  inverness: { label: "Highland Council: Church Street parking", href: "https://www.highland.gov.uk/directory-record/32/inverness-church-street" },
  trafficScotland: { label: "Traffic Scotland: current travel information", href: "https://www.traffic.gov.scot/travel-news" },
  dundee: { label: "Dundee City Council: Low Emission Zone", href: "https://www.dundeecity.gov.uk/service-area/city-development/sustainable-transport-and-roads/dundee-low-emission-zone-scheme-lez" },
  perth: { label: "Perth and Kinross Council: bay suspensions and dispensations", href: "https://www.pkc.gov.uk/article/22131/Bay-suspensions-and-dispensations" },
  stirling: { label: "Stirling Council: resident parking permits", href: "https://www.stirling.gov.uk/roads-transport-and-parking/parking-and-permits/apply-for-a-residents-parking-permit/" },
  fife: { label: "Fife Council: road maintenance and works", href: "https://www.fife.gov.uk/roads-travel-parking/roads-and-pavements/road-maintenance" },
  leeds: { label: "Leeds City Council: parking suspensions and dispensations", href: "https://www.leeds.gov.uk/parking/suspensions-and-dispensations" },
  falkirk: { label: "Falkirk Council: roads and parking", href: "https://www.falkirk.gov.uk/services/roads-transport/parking/" },
  northLanarkshire: { label: "North Lanarkshire Council: roads, transport and parking", href: "https://www.northlanarkshire.gov.uk/roads-transport-and-parking" },
  southLanarkshire: { label: "South Lanarkshire Council: roads and transport", href: "https://www.southlanarkshire.gov.uk/roads-and-transport" },
  renfrewshire: { label: "Renfrewshire Council: parking", href: "https://www.renfrewshire.gov.uk/article/1693/Parking" },
  westLothian: { label: "West Lothian Council: roads, transport and streets", href: "https://www.westlothian.gov.uk/roads-transport-and-streets" },
};

export const STAGED_ROUTE_PAGES_STAGE2: MovingRoutePage[] = [
  {
    slug: "glasgow-to-leeds",
    originSlug: "glasgow",
    destination: "Leeds",
    title: "Glasgow to Leeds removals",
    description: "Plan a Glasgow to Leeds house or flat move with LEZ vehicle checks, loading bay confirmation in Leeds and a confirmed key handover at both properties.",
    introduction: "A move from Glasgow to Leeds covers around 220 miles via the A74(M), M6 and M62. Start planning with the two property addresses rather than the two city names: what floor are you leaving, what vehicles can approach, and who is available to receive the load in Leeds?",
    sections: [
      { title: "Check Glasgow collection against the city LEZ first", body: "Glasgow's city-centre low-emission zone means the vehicle allocated to a central collection must meet the relevant emissions standard. Supply the full collection postcode so access can be confirmed before the date. For a tenement flat, photograph the close entry and the narrowest stair turn: these measurements help avoid an on-the-day decision about whether a large wardrobe will make it down in one piece.", source: sources.scottishLez },
      { title: "Resolve the Leeds unloading space before the van leaves Glasgow", body: "Leeds City Council has procedures for parking suspensions and dispensations covering furniture removals, subject to notice requirements. Check whether the Leeds destination is on a restricted street. Send photographs of the delivery street and the entrance to the building. Do not rely on an ordinary resident permit to cover a removal vehicle for the required loading duration.", source: sources.leeds },
      { title: "Prepare furniture for a long-distance single load", body: "Build a room-by-room inventory at the Glasgow property, including storage cupboards, loft items and garden furniture. Label boxes so the first in are the first out at Leeds. Identify every piece that needs dismantling and keep its fittings with the matching furniture. If the Glasgow property is part of a chain, confirm the vacancy time so the load is not left in an intermediary location without a plan." },
      { title: "Confirm the Leeds key handover in writing before the date", body: "A key-release estimate from a solicitor is not a confirmed handover time. Establish who will release the Leeds keys and by what time, then name a fallback contact for the property or building. If the tenancy ends in Glasgow before the Leeds keys are available, that gap needs to be in the plan, not discovered at the point of loading." },
    ],
    faqs: [
      { question: "How do I check the Glasgow collection postcode for LEZ compliance?", answer: "Use the Scottish Government's official low-emission zone map with the collection postcode. The zone applies to certain vehicle types; the check should happen before the vehicle is allocated, not on the collection morning." },
      { question: "Does the Leeds destination need a parking suspension?", answer: "It depends on the street and the intended stopping position. Check the signs and the Leeds City Council dispensation process. A suspension may require several working days' notice." },
      { question: "Can you stop at an additional Glasgow address before Leeds?", answer: "List any second collection address in the initial request. Adding a stop after loading starts is disruptive and may not match the van's capacity or the driver's planned route." },
    ],
  },
  {
    slug: "glasgow-to-bristol",
    originSlug: "glasgow",
    destination: "Bristol",
    title: "Glasgow to Bristol removals",
    description: "Prepare a Glasgow to Bristol house move with Scottish LEZ checks, Bristol Clean Air Zone vehicle compliance and access arrangements at both properties.",
    introduction: "Glasgow to Bristol is a long-distance move of over 400 miles. It needs a clear collection plan in Glasgow, a confirmed delivery arrangement in Bristol and enough lead time to address vehicle-compliance checks for both cities. Start with the full addresses and the furniture inventory.",
    sections: [
      { title: "Check the Glasgow collection against the LEZ boundary", body: "Glasgow's low-emission zone covers the city centre. Identify whether the collection address is inside and confirm the vehicle used meets the requirements. Also describe the street approach: whether it is pedestrianised during certain hours, whether there is a close entrance, and what route the furniture will take from the front door to the loading position.", source: sources.scottishLez },
      { title: "Verify the Bristol address and vehicle against the Clean Air Zone", body: "Bristol's Clean Air Zone covers the inner city and applies to certain vehicle types. Use the council's vehicle checker with the delivery address before confirming the move. Many Bristol streets near the city centre are terraced rows with no off-street access and restricted parking; confirm the unloading arrangement separately from the emissions check.", source: sources.bristol },
      { title: "Plan the journey timing around a confirmed delivery appointment", body: "A journey of more than 400 miles requires realistic planning for the driver's schedule. Give the Bristol recipient an honest arrival window rather than a fixed time. If access to the Bristol property has a specific lift or building appointment, that appointment governs the day's schedule, not the departure time from Glasgow." },
      { title: "Label the load to arrive in the right Bristol room", body: "Prepare room labels for the Bristol property before you start packing in Glasgow. Mark the boxes that must enter the Bristol property first, especially if the building has a service lift with a booking window. Keep essential items — medication, chargers, first-night supplies — separate from the consignment." },
    ],
    faqs: [
      { question: "Does the Bristol delivery van need to comply with the Clean Air Zone?", answer: "Certain vehicle types must comply if accessing the zone. Use the Bristol City Council vehicle checker with the confirmed delivery postcode and the proposed approach route." },
      { question: "How should I plan for the distance from Glasgow to Bristol?", answer: "Build the plan around a confirmed Bristol access time, not an approximate departure from Glasgow. The schedule should be agreed before booking so the travel leg is part of the arrangement." },
      { question: "Can the move happen over two days if needed?", answer: "Explain in the initial request if the Glasgow property will be handed back before the Bristol property is accessible. The plan must account for any gap between the two handovers." },
    ],
  },
  {
    slug: "glasgow-to-newcastle",
    originSlug: "glasgow",
    destination: "Newcastle upon Tyne",
    title: "Glasgow to Newcastle removals",
    description: "Prepare a Glasgow to Newcastle upon Tyne move with Scottish LEZ checks, tenement collection access and Newcastle unloading dispensation requirements.",
    introduction: "A Glasgow to Newcastle removal covers around 150 miles via the A74(M) and A1. Plan the collection from the Glasgow property details and the delivery from the specific Newcastle address, not the two city names.",
    sections: [
      { title: "Identify the Glasgow vehicle access before the move", body: "Glasgow's low-emission zone must be checked against the collection postcode and the allocated vehicle. For a tenement flat, describe the stair, the close entry width and the floor. If a lift is available in the building, confirm whether it can hold a standard double mattress. These factors determine the handling plan and the time needed at collection.", source: sources.scottishLez },
      { title: "Check whether the Newcastle address needs a dispensation", body: "Newcastle City Council's process includes furniture removals, subject to conditions and notice periods. Establish whether the delivery postcode is on a restricted street. If the property has its own service bay, note the dimensions and booking process and share those details in the move request.", source: sources.newcastle },
      { title: "Separate a Glasgow flat move from a Glasgow house move in the request", body: "A ground-floor house collection has different access from an upper-floor tenement. Describe the actual property: number of floors, whether the entrance is shared, and whether any furniture will need to be taken through a back lane. At the Newcastle end, describe whether a garden, driveway or communal entrance will be used, and who holds the key." },
      { title: "Keep both handover arrangements confirmed in writing", body: "Confirm the Glasgow key-return appointment and the Newcastle key-release separately. If a Glasgow lettings agency needs the property empty by a set time, include that constraint. Nominate a named Newcastle contact so the delivery does not depend on an informal understanding." },
    ],
    faqs: [
      { question: "Which route does a Glasgow to Newcastle van take?", answer: "The A74(M) and A1 is common; the M74 and A69 may suit deliveries to the west of Newcastle city centre. Provide both full postcodes and let access requirements guide the approach." },
      { question: "Can the move be completed in a single day?", answer: "The journey is feasible in one day depending on access times and load size. Confirm the Glasgow departure window and the Newcastle access time so the plan is realistic for both ends." },
      { question: "What if Newcastle parking is restricted near the property?", answer: "Describe the street and any signs you can photograph. Consult Newcastle City Council's guidance and obtain any required dispensation before the date." },
    ],
  },
  {
    slug: "edinburgh-to-birmingham",
    originSlug: "edinburgh",
    destination: "Birmingham",
    title: "Edinburgh to Birmingham removals",
    description: "Plan an Edinburgh to Birmingham house or flat move with dispensation applications, Birmingham Clean Air Zone compliance and property handover at both ends.",
    introduction: "An Edinburgh to Birmingham removal should be planned from both property addresses. Edinburgh's specific parking dispensation process covers the collection, and the Birmingham destination may need vehicle and loading-bay checks. Supply the full inventory and both access descriptions together.",
    sections: [
      { title: "Apply for an Edinburgh dispensation in advance of the collection", body: "Edinburgh Council manages dispensations and suspensions for furniture removals with notice requirements. Apply for the relevant collection postcode as early as possible with the address, proposed date and vehicle details. Do not assume a general residents' permit or a double-yellow-line tolerance will cover a removal vehicle for the required loading duration.", source: sources.edinburgh },
      { title: "Check the Birmingham delivery address against the Clean Air Zone", body: "Birmingham's Clean Air Zone is within the A4540 Middleway. Use the official vehicle checker with the delivery postcode and approach route. If the property is inside the zone, confirm the allocated vehicle's compliance before the move date. The unloading bay and building access requirements should be confirmed separately from the emissions check.", source: sources.birmingham },
      { title: "Describe both property types in the move request", body: "An Edinburgh tenement has different access from an Edinburgh new-build or a Victorian terrace. At Birmingham, a city-centre apartment has different loading from a semi-detached house with a driveway. Both descriptions matter for planning. Include photographs of each entrance, stair and proposed stopping position." },
      { title: "Coordinate key handover with both solicitors or agents", body: "For a purchase, establish the confirmed key-release times for both properties. A chain can delay either end independently. Name a contact who can answer the phone at each property on the move day, and identify any building rules about move-in or move-out hours at the Edinburgh or Birmingham address." },
    ],
    faqs: [
      { question: "How do I get a parking dispensation for an Edinburgh tenement collection?", answer: "Apply to Edinburgh Council's dispensations team with the address, proposed date and vehicle type. Check the council's current notice period before setting the date." },
      { question: "Does every Birmingham address need a Clean Air Zone check?", answer: "Only addresses within the A4540 Middleway require compliance. Use the official postcode checker to confirm. The unloading position may need separate confirmation regardless of zone status." },
      { question: "What inventory detail helps Edinburgh to Birmingham planning?", answer: "Room-by-room contents, dismantling requirements, floor and lift details at both addresses, key-release times and any fragile or specialist items. Complete information avoids negotiation on the day." },
    ],
  },
  {
    slug: "edinburgh-to-leeds",
    originSlug: "edinburgh",
    destination: "Leeds",
    title: "Edinburgh to Leeds removals",
    description: "Prepare Edinburgh to Leeds removals with council dispensation applications, loading bay checks, room-by-room inventory and confirmed key handovers.",
    introduction: "A move from Edinburgh to Leeds follows the A1(M) and covers around 200 miles. Edinburgh's specific dispensation process means parking must be arranged in advance at collection. At Leeds, identify the relevant loading authority for the delivery street before the day.",
    sections: [
      { title: "Arrange the Edinburgh dispensation before setting the date", body: "Edinburgh Council's dispensation process covers furniture removals but requires advance notice. The dispensation applies to a specific address and vehicle; do not proceed to book without confirming it is in place. For an Old Town or New Town Edinburgh address, also check any pedestrianisation hours that might restrict the vehicle approach at the planned collection time.", source: sources.edinburgh },
      { title: "Check the Leeds delivery street for loading restrictions", body: "Leeds City Council manages parking dispensations and suspensions for removals. Identify whether the delivery address is on a controlled street and whether a request is needed before the date. Send a photograph of the street signs and the proposed unloading position. A bay outside a terraced house may have time-limited restrictions that differ from the day you intend to arrive.", source: sources.leeds },
      { title: "Build a practical inventory for a flat in Edinburgh", body: "Edinburgh flats often have stone stair turrets with tight corners and no lift. Photograph the stair and the door opening of every large room. Measure sofas and wardrobes before deciding whether to dismantle them. A large wardrobe travelling via a tight Edinburgh tenement may require a different handling plan from a similar piece leaving a bungalow." },
      { title: "Give the Leeds recipient a delivery window, not a fixed time", body: "An Edinburgh loading slot and the A1(M) journey time produce an estimated arrival range. Communicate that range to the Leeds contact, especially if they must take time off work to receive the load. If the Leeds property has a building-management restriction on delivery times, establish it before confirming the Edinburgh collection date." },
    ],
    faqs: [
      { question: "What is the notice period for an Edinburgh dispensation?", answer: "Edinburgh Council's guidance sets out the current requirements. Apply as soon as the date is agreed; the notice period may be several working days and cannot always be shortened." },
      { question: "Does Leeds require a formal parking arrangement for a removal?", answer: "It depends on the specific street. Controlled areas may need a formal dispensation. Check the signs at the delivery address and the Leeds City Council guidance before assuming the vehicle can stop freely." },
      { question: "Can a large Edinburgh sofa come down a stone stair?", answer: "Some Edinburgh tenement stair dimensions prevent large furniture from passing whole. Photograph the stair and measure the sofa before booking; include those details so the move plan reflects the actual access." },
    ],
  },
  {
    slug: "aberdeen-to-birmingham",
    originSlug: "aberdeen",
    destination: "Birmingham",
    title: "Aberdeen to Birmingham removals",
    description: "Plan an Aberdeen to Birmingham house or flat move with LEZ collection checks, A90 journey planning, Birmingham Clean Air Zone compliance and delivery arrangements.",
    introduction: "A move from Aberdeen to Birmingham is a long-distance relocation of more than 500 miles. Planning should start with both property addresses: the access at each end, the furniture inventory and the handover arrangements. City LEZ and zone checks apply to both cities.",
    sections: [
      { title: "Use the Aberdeen LEZ check before confirming the vehicle", body: "Aberdeen has a low-emission zone covering the city centre. Check whether the collection postcode falls within it and confirm the allocated vehicle meets the standard. Aberdeen's granite tenements can have narrow stair turns and close entries that require a practical assessment before moving large furniture. Include photographs of the close and stairs in the move request.", source: sources.scottishLez },
      { title: "Allow for the full A90 journey time from Aberdeen south", body: "The A90 to M90 and then south via M9, M74 and M6 takes substantially longer from Aberdeen than from central Scotland. Allow for the full journey time when planning the Birmingham delivery window. Check Traffic Scotland for any A90 or M90 roadworks near the move date that could affect the departure time.", source: sources.trafficScotland },
      { title: "Verify the Birmingham delivery address for zone and access", body: "Birmingham's Clean Air Zone falls within the A4540 Middleway. Use the official vehicle checker with the delivery postcode and approach route. Confirm the unloading position separately: whether a service bay is available, whether the bay has restricted hours, and who at the building can confirm loading instructions.", source: sources.birmingham },
      { title: "Prepare the inventory and handover in writing before travelling", body: "List every room, its contents, dismantled pieces and the matching hardware. Confirm the Aberdeen key-return time and the Birmingham key-release time; if either involves a chain, describe the uncertainty in the move request rather than adjusting it later. A well-prepared Aberdeen inventory prevents delays at both ends." },
    ],
    faqs: [
      { question: "How does Aberdeen's LEZ affect the move?", answer: "The LEZ covers the city centre and certain vehicle types must comply. Provide the collection postcode so the vehicle can be confirmed before the move." },
      { question: "Is Aberdeen to Birmingham feasible in a single day?", answer: "The distance usually makes a single-day load-and-deliver arrangement difficult. Discuss the timeline in the move request, including overnight arrangements if the journey cannot complete before delivery is possible." },
      { question: "What information does a Birmingham delivery need from Aberdeen?", answer: "The full delivery postcode, building access instructions, floor and lift dimensions, zone status, unloading-bay details and the confirmed key-release time." },
    ],
  },
  {
    slug: "aberdeen-to-newcastle",
    originSlug: "aberdeen",
    destination: "Newcastle upon Tyne",
    title: "Aberdeen to Newcastle removals",
    description: "Prepare Aberdeen to Newcastle upon Tyne removals with LEZ vehicle checks, A90 journey planning and Newcastle unloading dispensation requirements.",
    introduction: "Aberdeen to Newcastle is a journey of around 220 miles, following the A90 to the A1(M) and into Newcastle from the north. Plan the collection from the Aberdeen property details and the delivery from the specific Newcastle address, allowing for the access requirements at both ends.",
    sections: [
      { title: "Check the Aberdeen collection postcode against the city LEZ", body: "Aberdeen's low-emission zone applies to the city centre. Confirm the collection address and the vehicle's compliance before agreeing the move date. Aberdeen's granite tenement buildings often have narrow stone stairs; photograph the close entrance and any tight turns so the load plan is correct before the team arrives.", source: sources.scottishLez },
      { title: "Use Traffic Scotland's travel information near the move date", body: "The A90 is the main arterial road between Aberdeen and central Scotland, and roadworks on this road or on the Tay crossing can significantly affect departure timing. Check Traffic Scotland closer to the move date and allow for an early departure if any constraint on the A90 or A1(M) is anticipated.", source: sources.trafficScotland },
      { title: "Arrange the Newcastle unloading space in advance", body: "Newcastle City Council's dispensation and suspension process covers furniture removals. Check the delivery street and whether an application is needed before the date, noting any notice requirements. A building with a dedicated service bay should also be checked: confirm the bay dimensions, booking process and access hours.", source: sources.newcastle },
      { title: "Keep the collection and delivery contacts separate", body: "For an Aberdeen to Newcastle move with different people handling each end, record the Aberdeen contact's name, phone and role, and the Newcastle recipient's name and instructions. Confirm who will accept the Newcastle delivery if the buyer or tenant is travelling separately. Avoid leaving the receiving arrangement to an informal understanding." },
    ],
    faqs: [
      { question: "Which route does the van take from Aberdeen to Newcastle?", answer: "The A90 south from Aberdeen to Dundee and Edinburgh, then the A1(M) south to Newcastle is typical. The exact approach to Newcastle depends on the delivery address." },
      { question: "Is the Forth Road Bridge crossing a factor for this route?", answer: "It can be, depending on current conditions. Check Traffic Scotland for bridge or approach information near the move date, especially if the plan requires a specific Newcastle delivery window." },
      { question: "Can someone else receive the Newcastle delivery on my behalf?", answer: "Yes, provide their name, contact number and clear room instructions. Confirm they have the keys and any building access codes or lift bookings needed for the property." },
    ],
  },
  {
    slug: "dundee-to-edinburgh",
    originSlug: "dundee",
    destination: "Edinburgh",
    title: "Dundee to Edinburgh removals",
    description: "Plan a Dundee to Edinburgh move with LEZ checks at both cities, Edinburgh dispensation requirements and practical collection access from Dundee.",
    introduction: "A Dundee to Edinburgh move involves two cities that each have low-emission zones and specific parking requirements. Identifying the collection access in Dundee and arranging the Edinburgh dispensation in advance are both practical steps that should be taken early.",
    sections: [
      { title: "Check the Dundee collection against the city LEZ", body: "Dundee's low-emission zone covers the inner city. Provide the full collection postcode so the vehicle can be confirmed before the date. Dundee's waterfront and some city-centre streets have specific loading arrangements; check whether the collection is in a restricted bay or a time-limited stopping area and photograph the proposed loading position.", source: sources.dundee },
      { title: "Apply for an Edinburgh dispensation before setting the collection date", body: "Edinburgh's dispensation process covers furniture removals but requires advance notice for the specific address. Apply with the delivery postcode, the proposed date and the vehicle type. Edinburgh's New Town and Old Town streets have different access constraints; an Old Town address may have restricted vehicle entry at certain hours.", source: sources.edinburgh },
      { title: "Describe both properties in the move request", body: "A Dundee flat on the fourth floor of a shared stair needs a different access plan from a Dundee semi-detached house with a private driveway. At Edinburgh, describe whether the property is in a tenement, a new-build or a converted flat. Include the floor number, stair details, any close entry codes and whether a service lift is available." },
      { title: "Confirm both handovers before travelling", body: "Even a short Scotland-to-Scotland move needs confirmed key arrangements. Establish whether the Dundee property must be returned before the Edinburgh property is accessible. If both coincide on the same day, confirm the sequence with both agencies or solicitors in writing. Identify a receiving contact in Edinburgh who can open the property and direct the load." },
    ],
    faqs: [
      { question: "Does a Dundee to Edinburgh move need LEZ checks at both ends?", answer: "Yes. Dundee and Edinburgh both have city-centre low-emission zones. The vehicle must comply with the standard for any collection or delivery inside either zone." },
      { question: "How long does the Edinburgh dispensation process take?", answer: "Edinburgh Council sets out its current notice requirements. Apply as soon as the date is confirmed; do not assume the dispensation will be available without the required lead time." },
      { question: "Can the van collect in Dundee and deliver in Edinburgh on the same day?", answer: "The journey is under 60 miles, so a same-day move is usually feasible. Confirm the access times at both ends before agreeing the date." },
    ],
  },
  {
    slug: "dundee-to-manchester",
    originSlug: "dundee",
    destination: "Manchester",
    title: "Dundee to Manchester removals",
    description: "Prepare Dundee to Manchester removals with city LEZ checks, correct loading bay guidance and an accurate furniture inventory for a long-distance move.",
    introduction: "A move from Dundee to Manchester travels the M74 and M6 corridor and needs a clear plan at both ends. Start with the full collection address in Dundee and the full delivery address in Manchester, then describe the property access and handover arrangements.",
    sections: [
      { title: "Verify the Dundee collection against the inner-city LEZ", body: "Dundee's low-emission zone applies in the inner city. Confirm the collection postcode and check the vehicle against the current requirements. For a waterfront or city-centre address, also photograph the proposed loading position and identify whether the bay is time-limited or requires prior notice to the council.", source: sources.dundee },
      { title: "Identify the Manchester unloading bay before the journey south", body: "Manchester City Council's guidance explains that loading bays are for active loading, with some limited to commercial vehicles. Ask the building manager or check the destination street signs to confirm the unloading arrangement. A controlled street may need an alternative stopping position. Settle this before the van leaves Dundee.", source: sources.manchester },
      { title: "Allow for the full journey time from Dundee", body: "Dundee is further north than Glasgow or Edinburgh, which makes the full journey longer. If Traffic Scotland reports issues on the M90 or A90 approaches, a departure buffer is useful. At Manchester, confirm whether the receiving property has a booking requirement for lifts or service bays before the collection date is set.", source: sources.trafficScotland },
      { title: "Build a room-by-room inventory with clear arrival labels", body: "A full house move from Dundee needs labelled boxes and a receiving plan at Manchester. Mark which boxes go to which room, keep fragile items separated and keep documents and medications with you. If someone else will receive the Manchester delivery, give them a copy of the room plan and the item list." },
    ],
    faqs: [
      { question: "Does a Dundee move need an LEZ vehicle check?", answer: "Yes, if the collection is within the Dundee LEZ. Use the full postcode to check the zone boundary, then confirm the vehicle against the current emissions standard." },
      { question: "How do I arrange Manchester loading bay access?", answer: "Check the street signs at the delivery address and consult Manchester City Council's guidance. Some bays are restricted to commercial vehicles or limited stopping times; confirm the arrangement before the day." },
      { question: "What if the Manchester delivery window conflicts with a building restriction?", answer: "Include any restriction at the time of booking, not on the day. A lift booking or porter requirement may govern when the furniture can be brought in. Build the Dundee collection time around that constraint." },
    ],
  },
  {
    slug: "inverness-to-manchester",
    originSlug: "inverness",
    destination: "Manchester",
    title: "Inverness to Manchester removals",
    description: "Prepare an Inverness to Manchester long-distance move with A9 travel considerations, collection access in the Highland capital and Manchester delivery logistics.",
    introduction: "Inverness to Manchester is one of the longer routes from Scotland, at over 350 miles. It involves Highland road conditions, the A9 corridor and the full length of the motorway south. A realistic schedule and confirmed access at both ends are essential before the date is set.",
    sections: [
      { title: "Identify the Inverness collection access and parking first", body: "Inverness city-centre streets have specific parking areas and some controlled loading bays. Check the proposed loading position against the street signage and photograph it. If the collection is outside the town centre, note the approach road, any lane width restrictions and whether a large van can reach the property without difficulty. Highland Council provides parking information for the city centre.", source: sources.inverness },
      { title: "Check Traffic Scotland for the A9 well before the move date", body: "The A9 is a key Highland arterial road with planned and unplanned disruptions. Check Traffic Scotland's travel news as the move date approaches and allow for an early departure if southbound roadworks or restrictions are anticipated. The M74 and M6 approach to Manchester also has variable traffic; a realistic schedule should account for both.", source: sources.trafficScotland },
      { title: "Confirm the Manchester delivery bay and building access early", body: "Manchester's loading bays have restrictions that differ by street. Check the delivery address signs and the Manchester City Council guidance. If the property is an apartment or managed building, establish the service-bay booking, lift dimensions and any time-restricted entry. An Inverness departure planned around the loading time in Manchester is more reliable than an assumed arrival.", source: sources.manchester },
      { title: "Plan the load as a single departure, not a staged collection", body: "An Inverness to Manchester move usually travels as one departure. Build the full inventory before the collection date, including any items in outbuildings, garages or loft spaces. If any items will remain at the Inverness property after the van departs, note who will retrieve them and when. A second trip at this distance must be planned in advance if anticipated." },
    ],
    faqs: [
      { question: "How long does Inverness to Manchester take?", answer: "Around 5 to 6 hours of driving, excluding loading, traffic and rest stops. The schedule should be built around the Manchester delivery access time." },
      { question: "Are there road restrictions between Inverness and the M74?", answer: "Seasonal and planned roadworks on the A9 and A74(M) can affect timings. Check Traffic Scotland before confirming the date and allow a buffer for unexpected delays." },
      { question: "What if the Manchester property has a lift booking?", answer: "Give the booking time in the move request from the start. The Inverness collection must allow the van to reach Manchester within the booking window. A missed lift appointment at a managed building can mean furniture sits in the lobby until the next available slot." },
    ],
  },
  {
    slug: "perth-to-london",
    originSlug: "perth",
    destination: "London",
    title: "Perth to London removals",
    description: "Prepare a Perth to London removal with dispensation checks, city-centre access, London unloading arrangements and confirmed property handovers.",
    introduction: "A Perth to London move is a long-distance relocation of around 450 miles. Perth city centre has specific loading requirements, and the London destination needs a separate unloading arrangement. Plan both ends from the full addresses before agreeing the date.",
    sections: [
      { title: "Check the Perth dispensation process for the collection address", body: "Perth and Kinross Council provides guidance on bay suspensions and dispensations for removals. Apply with the collection address and proposed date; the process may include a notice period. Perth's pedestrianised areas also have time-limited access; a collection close to the city centre needs access hours confirmed before the plan is finalised.", source: sources.perth },
      { title: "Arrange the London unloading address well in advance", body: "London's loading arrangements vary by borough and by whether the road is a TfL red route. For a TfL-managed street, check the signed loading bays and their restrictions. For a borough-managed street, contact the relevant council. Do not assume the delivery vehicle can stop freely outside the property; confirm the arrangement and any dispensation requirement before the Perth collection is booked.", source: sources.london },
      { title: "Allow realistic journey time for a Perth departure to London", body: "Perth is north of the Central Belt motorway network. Travelling to London takes over 8 hours of driving time. Build the schedule from the London delivery access time and work back. If the London property has a specific lift booking or goods-entrance appointment, that time governs when the vehicle should depart Perth." },
      { title: "Prepare a complete inventory at the Perth property", body: "A room-by-room Perth inventory with access notes makes the London delivery straightforward. Label boxes with room names and priority. Photograph the Perth access route so the loading sequence can be planned. If any London rooms need furniture placed in a specific order, communicate that in the room label." },
    ],
    faqs: [
      { question: "Does Perth have a pedestrian zone that affects collection?", answer: "Some Perth city-centre areas have time-limited access. Check the collection address and its access hours before setting the date, and confirm the applicable arrangement with Perth and Kinross Council." },
      { question: "How should I approach London red-route loading?", answer: "Identify whether the London delivery address faces a TfL red route. Check the signed loading bay restrictions and, if needed, the TfL guidance on loading for the public. Do not assume any stopping is permitted without confirming the specific bay rules." },
      { question: "Can the Perth furniture be delivered to a London upper-floor flat?", answer: "Describe the London floor, lift dimensions, any service-entrance requirement and the largest pieces. A stair carry at the London end for a long-distance move needs to be planned, not assumed." },
    ],
  },
  {
    slug: "stirling-to-london",
    originSlug: "stirling",
    destination: "London",
    title: "Stirling to London removals",
    description: "Prepare a Stirling to London house move with collection parking checks, London unloading requirements and confirmed handovers at both properties.",
    introduction: "A Stirling to London move starts with Stirling's specific street access and ends with the unloading arrangements at the London address. Both ends need attention before the date is fixed. Stirling's historic centre has narrow streets and controlled parking; London's loading rules depend on the borough and the type of road.",
    sections: [
      { title: "Check the Stirling collection postcode against current parking restrictions", body: "Stirling Council explains that a resident parking permit does not reserve a loading space or authorise parking in restricted bays. Check the street and loading position for the collection address. For a property near the castle or in the historic centre, confirm access hours and the proposed vehicle approach. Include photographs of the entrance route and any nearby restrictions.", source: sources.stirling },
      { title: "Resolve the London address and road authority before the date", body: "London's loading restrictions depend on whether the delivery road is managed by TfL or a borough. For a TfL red route, check the signed bay restrictions. For a borough road, contact the borough council. An unloading arrangement that seems obvious on a map may be restricted or require advance notice. Confirm before the date, not on arrival.", source: sources.london },
      { title: "Build a moving plan from the Stirling property outward", body: "A Stirling house move needs room-by-room listing, including attic, outbuildings and garden furniture. Photograph the entrance route and any turns furniture must make. If items are being dismantled, keep fittings with the matching piece. At London, describe the room for each piece so the delivery team does not need to improvise at the door." },
      { title: "Confirm the handover times before confirming the move", body: "For a house purchase or tenancy transition, establish when the Stirling keys must be returned and when the London keys can be collected. If the London end is part of a chain, describe that uncertainty in the booking request. Keep essential belongings separate from the consignment, especially if you are travelling independently." },
    ],
    faqs: [
      { question: "Does my Stirling parking arrangement cover the removal van?", answer: "A resident permit does not reserve space or authorise all bays. Check the specific street and any restrictions at the collection address, and tell us what loading arrangement is available." },
      { question: "How do I check London loading rules for my specific address?", answer: "Identify whether the road is managed by TfL or a borough council. Check the signed loading bays at the property. TfL's guidance covers red routes; borough councils manage other restrictions." },
      { question: "How should I prepare for a Stirling to London key-handover gap?", answer: "Write down both handover times and any uncertainty. If the Stirling keys must go back before the London keys are available, describe that gap in the booking. Do not assume the schedule can absorb it without a plan." },
    ],
  },
  {
    slug: "stirling-to-edinburgh",
    originSlug: "stirling",
    destination: "Edinburgh",
    title: "Stirling to Edinburgh removals",
    description: "Plan a Stirling to Edinburgh house move with collection parking restrictions, Edinburgh dispensation requirements and practical access at both properties.",
    introduction: "A Stirling to Edinburgh move covers around 35 miles and can usually be completed in a single day. Both cities have specific parking restrictions: Stirling's resident permits do not reserve loading space, and Edinburgh requires advance dispensation applications for the delivery address.",
    sections: [
      { title: "Check the Stirling street and collection access carefully", body: "Stirling Council's guidance states that a resident parking permit does not guarantee a loading space or permit parking in certain bays. Identify the specific restriction at the collection address and determine whether the vehicle needs a dedicated loading position. For a property in the historic centre or near the castle, also check access hours for the approach road.", source: sources.stirling },
      { title: "Apply for the Edinburgh dispensation in advance", body: "Edinburgh Council's dispensation process has notice requirements. Apply with the full delivery postcode, the planned date and the vehicle type as soon as the date is set. An Old Town or New Town Edinburgh address may have controlled-zone access; confirm whether the vehicle approach is unrestricted at the planned delivery time.", source: sources.edinburgh },
      { title: "Describe both properties precisely in the move request", body: "A Stirling Victorian terrace and an Edinburgh new-build flat need entirely different access plans. For each property, identify the floor, number of stairs, any shared entrance or close access code, and the route furniture will take from the front door to the loading or delivery position. Photographs of both entrances are useful." },
      { title: "Plan the key handover before confirming the date", body: "Even a short move needs confirmed handover arrangements. Check when the Stirling property must be vacated and when the Edinburgh property is accessible. If an agent or solicitor manages either key, get written confirmation before committing to a date. Nominate a named contact for each address who can open the door and answer questions on the move day." },
    ],
    faqs: [
      { question: "Can Stirling to Edinburgh be done in a single day?", answer: "Yes, for most moves. Confirm the access windows at both addresses — the Stirling loading time and the Edinburgh delivery time — before treating it as a single-day job." },
      { question: "Does Edinburgh always require a formal dispensation?", answer: "Edinburgh Council requires dispensations for removals on restricted streets. Whether your delivery address needs one depends on the specific postcode and road type. Apply in advance to avoid a problem on the day." },
      { question: "What van size does a typical two-bedroom Stirling move need?", answer: "Van size depends on the number of items, not just bedrooms. Build a room-by-room inventory and include that in the move request so the right vehicle can be confirmed." },
    ],
  },
  {
    slug: "falkirk-to-london",
    originSlug: "falkirk",
    destination: "London",
    title: "Falkirk to London removals",
    description: "Prepare a Falkirk to London removal with collection parking checks, long-distance load planning, London unloading requirements and property handover.",
    introduction: "A move from Falkirk to London travels south via the M9 or M80, then the M74 and M6, covering around 400 miles. The collection side needs the Falkirk street access confirmed, and the London delivery needs the unloading arrangement settled well in advance.",
    sections: [
      { title: "Check the Falkirk collection address for loading restrictions", body: "Falkirk Council manages parking and loading restrictions for the town. Check the proposed collection street and loading position, particularly if the property is near the town centre or a controlled parking zone. Photograph the vehicle approach, the front path and the proposed stopping position. Provide the full address so access requirements can be confirmed before agreeing the date.", source: sources.falkirk },
      { title: "Arrange the London unloading address in advance", body: "London loading arrangements depend on whether the delivery road is managed by TfL or a borough. Identify the relevant authority for the delivery postcode. For a TfL red route, check the signed bay restrictions before the move. For a borough road, contact the council. An arrangement that seems available from a map may be restricted; settle it before the Falkirk departure is booked.", source: sources.london },
      { title: "Prepare the Falkirk inventory for a single long-distance load", body: "List all rooms, outbuildings and any garage or loft items at the Falkirk property. Label boxes so the London rooms can receive them without opening each one on arrival. Mark any dismantled furniture clearly. Keep essential belongings — keys, documents, medication — outside the main load, especially if you are travelling separately to London." },
      { title: "Confirm the London handover before the Falkirk collection date", body: "Long-distance moves need confirmed handover times at both ends. Establish when the London keys are released and whether any chain still needs to complete. Write down who releases the keys and who can answer the phone at the London property on delivery day. If the receiving property is managed, also confirm any lift-booking or concierge requirement." },
    ],
    faqs: [
      { question: "Does a Falkirk town-centre collection need a parking arrangement?", answer: "Check the specific street and any loading restrictions. Photograph the proposed stopping position and describe the access route from the door to the vehicle. Falkirk Council can confirm any applicable requirement for the address." },
      { question: "How do I determine the London road authority for my delivery?", answer: "Use the London borough map and the TfL road network map. A TfL red-route address uses TfL's loading guidance; a borough-road address uses the borough council's process." },
      { question: "What if the London property is not ready when the Falkirk van arrives?", answer: "Agree the delivery arrangement before confirming the Falkirk collection. A confirmed London key time governs the schedule. If there is uncertainty at the London end, build that into the plan rather than departing Falkirk without a confirmed receiving arrangement." },
    ],
  },
  {
    slug: "falkirk-to-manchester",
    originSlug: "falkirk",
    destination: "Manchester",
    title: "Falkirk to Manchester removals",
    description: "Prepare a Falkirk to Manchester house or flat move with collection access, motorway route planning, Manchester loading checks and property handover.",
    introduction: "A Falkirk to Manchester move follows the M80 and M74 south through the Central Belt, then the M6 into Manchester. The collection side needs the Falkirk loading position confirmed, and the Manchester delivery needs the bay and building access settled before the van leaves.",
    sections: [
      { title: "Identify the Falkirk collection position and any access restriction", body: "Falkirk Council manages roads and parking across the town. Check whether the collection address falls within a controlled area and whether the van requires a dedicated stopping arrangement. Photograph the loading route from the entrance and any time-restricted signs near the property.", source: sources.falkirk },
      { title: "Confirm the Manchester loading bay before the move date", body: "Manchester City Council's guidance confirms that loading bays serve active loading, with some restricted to commercial vehicles. Identify the bay nearest the Manchester delivery address and its restrictions. If the property has a managed entrance or service bay, obtain the booking details. Do not rely on informal observation of a parking bay as a reliable unloading arrangement.", source: sources.manchester },
      { title: "Plan a realistic departure from Falkirk for the Manchester window", body: "Falkirk is around 260 miles from Manchester. Allow for motorway traffic, particularly on the M74 and M6, when planning departure time. If the Manchester recipient has a specific arrival window for a building service lift or goods entrance, work backwards from that time when agreeing the Falkirk collection slot." },
      { title: "List both addresses with full access detail", body: "Give the exact Falkirk address, floor, entrance and largest items. Give the Manchester address, floor, lift, service bay and recipient contact. These details prevent delays at both ends and allow the correct vehicle to be confirmed for the job." },
    ],
    faqs: [
      { question: "How long is the drive from Falkirk to Manchester?", answer: "Around 4 to 5 hours of driving, depending on traffic. The schedule should be built from the Manchester access time, working back to a Falkirk loading start." },
      { question: "Does a Falkirk suburban collection have the same restrictions as the town centre?", answer: "Not necessarily. Controlled zones vary by street. Check the specific address and photograph the loading position. Provide the postcode in the move request so the correct access plan can be confirmed." },
      { question: "What if the Manchester building has a lift with restricted booking hours?", answer: "Provide the booking window in the move request. A Falkirk departure must allow the van to arrive before the lift window closes; plan accordingly." },
    ],
  },
  {
    slug: "motherwell-to-london",
    originSlug: "motherwell",
    destination: "London",
    title: "Motherwell to London removals",
    description: "Prepare a Motherwell to London house move with North Lanarkshire collection access, M74 route logistics, London unloading requirements and property handover.",
    introduction: "A move from Motherwell to London follows the M74 south from North Lanarkshire and travels the full length of the M6 and M1 or M40. The M74 is close to Motherwell town centre, giving relatively direct access to the motorway. The London delivery needs the unloading arrangement settled well before the day.",
    sections: [
      { title: "Check the Motherwell collection address for parking requirements", body: "North Lanarkshire Council manages roads and parking across the area, including Motherwell. Check the collection street for any controlled parking, loading restrictions or pedestrian times. Photograph the proposed loading position and the entrance route. If the property is in a controlled area, confirm the applicable arrangement with North Lanarkshire before setting the date.", source: sources.northLanarkshire },
      { title: "Settle the London unloading address before the van leaves", body: "London's loading rules depend on the borough and whether the delivery road is on the TfL network. Identify the authority for the delivery address and check the signed bay restrictions. If the London property is managed, obtain service-bay access instructions and any concierge contact. A confirmed arrangement at the London end prevents delays after a long motorway journey.", source: sources.london },
      { title: "Build an inventory that reflects the Motherwell property in full", body: "List every room and its contents, including outbuildings, any garage items and garden furniture. Mark which boxes should be loaded last so they come out first in London. If any furniture needs dismantling in Motherwell, prepare the pieces and keep all fittings labelled and bagged together. Describe any access challenges at the entrance path or internal stair." },
      { title: "Confirm both handovers with named contacts", body: "Establish the Motherwell key-return time and the London key-release time separately. Confirm who manages each handover, particularly if an agent or solicitor is involved at either end. Name a fallback contact for each address. For a managed London building, add the concierge contact and any access instructions." },
    ],
    faqs: [
      { question: "Is Motherwell's proximity to the M74 an advantage for this move?", answer: "It reduces the time from collection to motorway. The total journey still depends on loading time in Motherwell and the delivery access time in London; plan from those constraints." },
      { question: "Which London borough will manage my delivery street?", answer: "Use the full delivery postcode to identify the borough. Check the borough council's parking guidance for the specific street and loading requirements." },
      { question: "Can someone else receive the London delivery on my behalf?", answer: "Yes. Provide their name, contact number and a copy of the room plan. Confirm they have the property keys and any lift or bay booking reference." },
    ],
  },
  {
    slug: "hamilton-to-london",
    originSlug: "hamilton",
    destination: "London",
    title: "Hamilton to London removals",
    description: "Prepare a Hamilton, South Lanarkshire to London removal with collection access, M74 route logistics, London unloading checks and confirmed property handovers.",
    introduction: "Hamilton in South Lanarkshire sits close to the M74, giving direct access to the southbound motorway network. A move to London still needs a clear collection plan in Hamilton and a confirmed unloading arrangement in London before the date is agreed.",
    sections: [
      { title: "Check the Hamilton collection street for parking and loading", body: "South Lanarkshire Council manages roads and parking across the area, including Hamilton. Identify any controlled parking, loading restrictions or time-limited bays at the collection address. Photograph the front entrance, the proposed vehicle stopping point and any restrictions nearby. If the property is in the town centre, confirm whether the approach road has restricted hours.", source: sources.southLanarkshire },
      { title: "Settle the London delivery arrangement in advance", body: "London loading rules differ by borough and by whether the road is on the TfL network. Use the delivery postcode to identify the road authority and check the relevant loading guidance. A TfL red-route address needs the signed bay restrictions confirmed; a borough road needs the borough council's parking guidance. Settle the arrangement before the Hamilton collection is booked.", source: sources.london },
      { title: "Prepare the Hamilton inventory with road access in mind", body: "List every room and describe any access path between the front door and the loading position. A Hamilton property with a shared driveway or a narrow front path needs the access route recorded. Label the boxes for London rooms and identify which pieces need dismantling. If any items are being added to the load from a different address, include that in the move request from the start." },
      { title: "Name a receiving contact in London with full instructions", body: "Establish who will accept the London delivery, confirm they have the keys, and give them a room plan and item list. If the London property is in a managed building, add the concierge contact details, any lift booking and the delivery hours the building allows. A long journey from Hamilton ends well when the London access is fully confirmed in advance." },
    ],
    faqs: [
      { question: "Does Hamilton have specific loading restrictions for removals?", answer: "South Lanarkshire Council manages local roads. Check the specific collection address for controlled parking or time-limited loading. Photograph the signs and describe the access route in the move request." },
      { question: "What makes a Hamilton to London quote accurate?", answer: "Both full addresses, floor and access details, a room-by-room inventory, dismantling requirements, key times and the receiving contact in London. Partial information delays planning." },
      { question: "How far in advance should I arrange the London unloading?", answer: "As early as possible. Some London boroughs have notice requirements for parking dispensations. Identifying the authority and applying early is better than resolving a street restriction on the day of arrival." },
    ],
  },
  {
    slug: "paisley-to-london",
    originSlug: "paisley",
    destination: "London",
    title: "Paisley to London removals",
    description: "Prepare a Paisley to London removal with Renfrewshire collection access, M8 motorway logistics, London road-authority checks and property handover.",
    introduction: "A Paisley to London move travels via the M8 into Glasgow, then south on the M74 and M6. Renfrewshire Council manages parking in Paisley and surrounding areas. At the London end, identify the road authority for the delivery street and confirm the loading arrangement before the van leaves.",
    sections: [
      { title: "Check the Paisley collection address for loading restrictions", body: "Renfrewshire Council manages parking and loading across Paisley. Check the collection street for controlled parking, time-limited bays or any access restriction near the property. Photograph the proposed vehicle stopping position and the entrance route. If the property is in Paisley town centre, confirm access hours and whether any pedestrianisation affects the vehicle approach.", source: sources.renfrewshire },
      { title: "Resolve the London unloading arrangement before the collection date", body: "Use the full London delivery postcode to identify whether the road is managed by TfL or a borough council. For a TfL red route, check the signed loading bays and their restrictions. For a borough street, contact the borough council. Some London streets near residential areas are privately managed; check the entrance sign and ask the building manager for the correct instructions.", source: sources.london },
      { title: "Prepare the Paisley property inventory with access notes", body: "List every room at the Paisley property, including any garage or outbuilding items. Describe the access from the entrance to the loading position, noting any steps, gates or tight turns. If any items are coming from a second Renfrewshire address, list them separately and include that address in the move request from the start." },
      { title: "Confirm both handovers and the London receiving contact", body: "Establish the Paisley key-return time and the London key-release time. Name a receiving contact in London with the keys, a room plan and instructions for any building access requirement. If the London property is in a managed block, add concierge contact details and delivery hours. Confirm both handovers in writing before committing to the collection date." },
    ],
    faqs: [
      { question: "Does Paisley town centre have access restrictions for large vehicles?", answer: "Some areas of Paisley town centre have limited vehicle access. Check the collection address and access hours before confirming the date. Photograph the approach route and describe any restriction in the move request." },
      { question: "What if my London delivery street has no obvious loading bay?", answer: "Contact the road authority for the delivery postcode. Some streets have informal loading tolerances; others require a formal arrangement. Do not assume availability without checking." },
      { question: "Can items from two Renfrewshire addresses travel in the same van?", answer: "Yes, but list both addresses and both inventories in the move request. A second collection point affects the loading sequence, the vehicle capacity and the departure time." },
    ],
  },
  {
    slug: "livingston-to-london",
    originSlug: "livingston",
    destination: "London",
    title: "Livingston to London removals",
    description: "Prepare a Livingston, West Lothian to London removal with town-centre access checks, motorway logistics, London unloading requirements and property handover.",
    introduction: "Livingston is a planned New Town in West Lothian with direct M8 and M9 access. A move to London from Livingston follows the M8 or M9 south to the M74 and M6. West Lothian Council manages roads and parking in the area. The London delivery needs its own access plan regardless of how straightforward the Livingston departure is.",
    sections: [
      { title: "Check the Livingston collection address for loading access", body: "West Lothian Council manages roads and parking across Livingston. Livingston's New Town layout includes pedestrian zones, bus routes and parking areas that can restrict where a removal vehicle stops. Check the specific collection address for any loading restriction and photograph the proposed stopping position and entrance route.", source: sources.westLothian },
      { title: "Settle the London delivery arrangement before departing West Lothian", body: "London's loading rules vary by borough and TfL road status. Identify the authority for the delivery postcode before the move date. A TfL red-route delivery needs the signed bay rules confirmed; a borough street needs the borough council's guidance. Confirm the arrangement in writing rather than assuming availability on arrival.", source: sources.london },
      { title: "Build the Livingston inventory around the property type", body: "Livingston properties include a range of house types, from post-war semis to more recent estate houses and flats. The inventory should reflect the actual property: number of floors, any difficult access, largest items and any dismantling needed. Include items in garages, outbuildings or storage areas. Label boxes with room names for the London destination." },
      { title: "Confirm both handovers with named contacts in advance", body: "Establish the Livingston property-return date and the London key-release time. Describe any uncertainty, particularly in a chain, before the move date is agreed. Name a London receiving contact with the property keys and a clear room plan. Add any managed-building access instructions to the move request." },
    ],
    faqs: [
      { question: "Does Livingston's New Town layout affect removal access?", answer: "Livingston's pedestrian areas and bus-priority roads can restrict certain access routes. Check the specific collection address and approach route. West Lothian Council manages local roads." },
      { question: "Which motorway does the van use from Livingston to London?", answer: "M8 or M9 to M74 to M6, then M1 or M40 to London, depending on the delivery address. Provide the full postcode so the best approach can be confirmed." },
      { question: "How should I handle an uncertain London move-in date?", answer: "Describe the uncertainty in the booking request. If the London property is part of a chain, note which link is unconfirmed. The Livingston collection date should not be set until the London access is confirmed or the gap is planned for." },
    ],
  },
  {
    slug: "kirkcaldy-to-london",
    originSlug: "kirkcaldy",
    destination: "London",
    title: "Kirkcaldy to London removals",
    description: "Prepare a Kirkcaldy to London removal with Fife road information, Forth Road Bridge planning, London unloading checks and confirmed property handovers.",
    introduction: "A move from Kirkcaldy to London involves crossing the Forth Road Bridge or Queensferry Crossing and travelling south via the M90, M9 and M74. Fife Council manages roads in Kirkcaldy and the approach from the coast. Start with the full Kirkcaldy collection address and the full London delivery address.",
    sections: [
      { title: "Check Fife road conditions before finalising the Kirkcaldy departure", body: "Fife Council provides information on road maintenance and works affecting local routes. Check for any roadworks on the A92 or the approach to the Forth Road Bridge near the move date. A Kirkcaldy departure needs the A92 approach confirmed as part of the plan, especially if the move is time-sensitive at the London end.", source: sources.fife },
      { title: "Identify the Kirkcaldy loading position and street access", body: "Kirkcaldy town-centre streets and seafront areas have specific parking arrangements. Check the loading position for the collection address and photograph the proposed stopping point. If the property is in a residential area outside the centre, confirm whether the street has controlled parking or any restriction that could affect the move day." },
      { title: "Settle the London delivery and road authority before the Kirkcaldy date", body: "Use the London delivery postcode to identify whether the road is on the TfL network or managed by a borough. Confirm the applicable loading arrangement: for a TfL red route, check the bay restrictions; for a borough road, contact the council. For a managed London building, obtain the service-bay booking, lift dimensions and permitted delivery hours.", source: sources.london },
      { title: "Build the Kirkcaldy inventory with London room labels", body: "List every room at the Kirkcaldy property, including any attic, garage or outbuilding items. Label boxes with the destination room in London. Identify any pieces that need dismantling and keep their fittings labelled and bagged. Name a London contact with the property keys and a copy of the room plan so the delivery proceeds without improvisation." },
    ],
    faqs: [
      { question: "Does a Kirkcaldy move use the Forth Road Bridge?", answer: "Yes. The A92 from Kirkcaldy connects to the Forth Road Bridge or the Queensferry Crossing. Check Fife Council and Traffic Scotland for any crossing or approach roadworks near the move date." },
      { question: "How does Kirkcaldy town-centre loading work for a removal?", answer: "Check the specific street for any loading restriction or controlled parking. Photograph the signs and the proposed stopping position. For a property with limited street frontage, describe any alternative access route." },
      { question: "What is the best way to prepare a London receiving contact?", answer: "Give them the room plan, the item list, the property keys and any managed-building access instructions. Confirm they can accept the delivery and answer questions on the day." },
    ],
  },
];
