export interface MovingRoutePage {
  slug: string;
  originSlug: string;
  destination: string;
  title: string;
  description: string;
  introduction: string;
  sections: { title: string; body: string; source?: { label: string; href: string } }[];
  faqs: { question: string; answer: string }[];
}

const sources = {
  scottishLez: { label: "Scottish Government: low emission zones", href: "https://www.mygov.scot/low-emission-zones" },
  edinburgh: { label: "Edinburgh Council: dispensations and suspensions", href: "https://www.edinburgh.gov.uk/parking-spaces/dispensations-suspensions" },
  london: { label: "Transport for London: loading on red routes", href: "https://tfl.gov.uk/modes/driving/red-routes/rules-of-red-routes/loading-for-the-public" },
  manchester: { label: "Manchester City Council: loading bays", href: "https://www.manchester.gov.uk/parking/tickets-and-fines/parking-restrictions/parking-restrictions/parking-in-a-loading-bay" },
  birmingham: { label: "Transport for West Midlands: Birmingham Clean Air Zone", href: "https://www.tfwm.org.uk/plan-your-journey/ways-to-travel/driving-in-the-west-midlands/birmingham-clean-air-zone/" },
  cardiff: { label: "Cardiff Council: parking and loading restrictions", href: "https://cardiff.gov.uk/contraventions" },
  bristol: { label: "Bristol City Council: Clean Air Zone vehicle checker", href: "https://www.bristol.gov.uk/residents/streets-travel/bristols-caz/charges-and-vehicle-checker" },
  newcastle: { label: "Newcastle City Council: parking dispensations", href: "https://new.newcastle.gov.uk/parking/dispensations-and-suspensions" },
  inverness: { label: "Highland Council: Church Street parking", href: "https://www.highland.gov.uk/directory-record/32/inverness-church-street" },
  trafficScotland: { label: "Traffic Scotland: current travel information", href: "https://www.traffic.gov.scot/travel-news" },
  dundee: { label: "Dundee City Council: Low Emission Zone", href: "https://www.dundeecity.gov.uk/service-area/city-development/sustainable-transport-and-roads/dundee-low-emission-zone-scheme-lez" },
  perth: { label: "Perth and Kinross Council: bay suspensions and dispensations", href: "https://www.pkc.gov.uk/article/22131/Bay-suspensions-and-dispensations" },
  stirling: { label: "Stirling Council: resident parking permits", href: "https://www.stirling.gov.uk/roads-transport-and-parking/parking-and-permits/apply-for-a-residents-parking-permit/" },
  fife: { label: "Fife Council: road maintenance and works", href: "https://www.fife.gov.uk/roads-travel-parking/roads-and-pavements/road-maintenance" },
};

// An authored allowlist, not an origin/destination cross product.
export const MOVING_ROUTE_PAGES: MovingRoutePage[] = [
  {
    slug: "glasgow-to-london",
    originSlug: "glasgow",
    destination: "London",
    title: "Glasgow to London removals",
    description: "Plan a move from Glasgow to London around tenement access, the London unloading address, furniture preparation and key handover.",
    introduction: "A Glasgow to London move needs a workable collection plan and a confirmed place to unload at the other end. Tell us which floor you are leaving, what is travelling and who can admit the team at the London address. This guide helps you prepare those details before booking.",
    sections: [
      { title: "Start with the Glasgow close and collection street", body: "If you are leaving a tenement, measure the narrowest stair turn and identify where large furniture can be prepared without blocking the shared entrance. Photograph the street approach as well as the flat door. Glasgow has a city-centre LEZ; give the exact collection postcode so vehicle access can be checked before a collection window is agreed.", source: sources.scottishLez },
      { title: "Identify the London road authority before unloading", body: "Ask the recipient whether the entrance faces a TfL red route or a borough-managed street. TfL loading bays have signed restrictions and are not waiting spaces. Send a photograph of the bay sign and the distance to the building entrance. If a bay cannot accommodate the proposed unloading, resolve the permitted stopping arrangement before the van leaves Glasgow.", source: sources.london },
      { title: "Coordinate keys with the person receiving the move", body: "For a tenancy change or purchase, distinguish the expected key-release time from an actual confirmed handover. Nominate someone who can answer the phone, open the London building and show the correct flat or room. Tell us about concierge hours, goods-lift reservations and separate service entrances while planning; a postcode alone does not describe how the furniture reaches the property." },
      { title: "Prepare furniture for one planned long-distance load", body: "Create a room-by-room list at the Glasgow home, including storage cupboards and any pieces being dismantled. Mark the boxes you need first in London and keep keys, documents and medication with you. Explain any extra collection or delivery address in advance so the loading order can suit the whole move instead of discovering a second destination after loading." },
    ],
    faqs: [
      { question: "Can you collect from a Glasgow upper-floor flat for a London move?", answer: "Include the floor, stairs, lift details and the largest items in your request. Photos of the close and stair turns help assess the handling needed, particularly where a sofa or wardrobe will not fit in a lift." },
      { question: "Will the London address need a parking arrangement?", answer: "It depends on the exact street and unloading duration. Check the signs and road authority, and tell us if the building has a bookable service bay. A resident's ordinary parking arrangement may not resolve a removal vehicle's needs." },
      { question: "Can the delivery time match my London key collection?", answer: "Give the expected handover time and any building access deadline before booking. The schedule needs to account for loading and the journey; agree the delivery arrangement rather than assuming a fixed arrival from the city names." },
    ],
  },
  {
    slug: "glasgow-to-manchester",
    originSlug: "glasgow",
    destination: "Manchester",
    title: "Glasgow to Manchester moving service",
    description: "Prepare a Glasgow to Manchester move with a clear furniture list, legal loading space, apartment access and an agreed delivery handover.",
    introduction: "Moving from a Glasgow home into a Manchester apartment can involve two very different handling arrangements. A shared stair at collection and a controlled delivery entrance at arrival should both be included in the plan. Start with the full addresses, the furniture list and any access appointments.",
    sections: [
      { title: "Separate Glasgow vehicle access from furniture access", body: "Check whether the Glasgow collection is inside the LEZ, then describe the route between the front door and the van. A compliant vehicle still needs a suitable loading position. For a flat, add the number of stair flights, any locked close door and whether furniture must turn on a landing. These details help determine the practical collection sequence.", source: sources.scottishLez },
      { title: "Check the Manchester bay and apartment entrance together", body: "Manchester's council says loading bays are for loading activity, with some limited to commercial vehicles. Ask for the actual bay sign near the destination instead of relying on a map's parking symbol. If the apartment entrance is around the building from the bay, record the carrying distance and confirm whether a separate goods entrance is required.", source: sources.manchester },
      { title: "Reserve building facilities before finalising the move", body: "Ask the Manchester managing agent whether a goods lift needs a reservation, what its door opening measures and who releases the access barrier. Match those answers to your largest Glasgow items. If a bed or desk needs dismantling to use the lift, agree that task beforehand and keep its fittings labelled with the matching furniture." },
      { title: "Give the recipient a room and item checklist", body: "Prepare a short arrival list with room names, box labels and the pieces that need to enter first. This is useful when the person meeting the van in Manchester is different from the person present in Glasgow. Include the recipient's phone number and a plan for access changes so the team is not left negotiating with a concierge without instructions." },
    ],
    faqs: [
      { question: "Is a single furniture item suitable for Glasgow to Manchester?", answer: "Describe the item, its dimensions, both addresses and the help required at each end. A single sofa can still need careful stair or lift planning; the item count alone does not establish the handling needed." },
      { question: "Should I book the Manchester lift first?", answer: "Find out its availability and restrictions early, then coordinate a suitable window with the move. Do not treat a lift booking as confirmation of the vehicle arrival time until the transport arrangement is agreed." },
      { question: "What if the delivery is outside Manchester City Council's area?", answer: "Use the full destination postcode and the appropriate local council's parking guidance. A Greater Manchester postal address does not mean every street has the same authority or loading rules." },
    ],
  },
  {
    slug: "glasgow-to-birmingham",
    originSlug: "glasgow",
    destination: "Birmingham",
    title: "Glasgow to Birmingham removals",
    description: "Plan Glasgow to Birmingham furniture and house moves with collection access, Birmingham zone checks, inventory and delivery arrangements.",
    introduction: "A Glasgow to Birmingham relocation should be planned from the two property entrances, not just the two city centres. The destination may involve a city-centre service bay, a driveway or an upper-floor flat. Supply those details alongside the Glasgow collection information to build a useful moving request.",
    sections: [
      { title: "Check the Glasgow collection vehicle against the address", body: "Glasgow's centre includes an LEZ, so the approach to the collection property needs checking before the vehicle is allocated. Also identify the doorway and any rear access that could suit large furniture. If the front route includes steps, record them even where the property is described as ground floor; that detail matters when planning a loaded appliance or bookcase.", source: sources.scottishLez },
      { title: "Locate the Birmingham destination relative to the zone", body: "Birmingham's Clean Air Zone sits inside the A4540 Middleway, excluding the ring road itself. Check the delivery address and the proposed approach, then verify the assigned vehicle through the official guidance. A zone check and permission to occupy a loading bay are separate tasks, so ask the building manager where the actual unload should take place.", source: sources.birmingham },
      { title: "Include work equipment as well as household boxes", body: "If the Glasgow move combines a home and a home office, list desks, monitors and document boxes separately from ordinary bedroom furniture. Photograph fragile equipment before packing and identify items requiring specialist preparation. At the Birmingham end, nominate a room for sealed work boxes so they do not need to be opened in a shared entrance while other furniture is arriving." },
      { title: "Plan a handover that works when keys are released late", body: "Tell us when the Glasgow property must be empty and when you can physically enter the Birmingham property. If those conditions do not align, discuss the available arrangements before confirming the move. Have a named recipient and an alternative contact; do not leave the delivery dependent on an estate agent's estimated call while the vehicle is already on the way." },
    ],
    faqs: [
      { question: "Does every Birmingham delivery enter the Clean Air Zone?", answer: "No. It depends on the address and approach. Provide the destination postcode and loading entrance, and check the current official map and vehicle checker when arranging the job." },
      { question: "Can household and home-office items travel in the same move?", answer: "List everything together but identify screens, IT equipment and confidential boxes clearly. Confirm any packing or dismantling requirements before booking rather than assuming the team can prepare specialist equipment on arrival." },
      { question: "What should I send for a Glasgow to Birmingham quote?", answer: "Both full addresses, the item or room inventory, access photographs, floor and lift details, preferred dates and the two key-handover windows. Include extra stops and furniture assembly requirements in the same request." },
    ],
  },
  {
    slug: "glasgow-to-cardiff",
    originSlug: "glasgow",
    destination: "Cardiff",
    title: "Glasgow to Cardiff removals",
    description: "Prepare your move from Glasgow to Cardiff with parking checks, practical furniture access, labelled packing and a confirmed receiving contact.",
    introduction: "For a move from Glasgow to Cardiff, the destination street and property layout deserve attention before packing is finished. A house with a narrow front path needs a different unload from an apartment with managed access. Share photos from both ends so the plan reflects the move you actually have.",
    sections: [
      { title: "Make the Glasgow departure ready before the travel leg", body: "Choose which furniture needs dismantling at collection and keep its screws, feet and brackets labelled. Describe any narrow Glasgow close or communal stairs in your request so the team can plan the handling. For a central address, check the collection against the Scottish LEZ guidance before confirming the vehicle; completing those checks late can disrupt the departure sequence.", source: sources.scottishLez },
      { title: "Read Cardiff kerb markings as well as parking signs", body: "Cardiff's guidance distinguishes waiting restrictions from restrictions on loading. Kerb marks and the accompanying signs therefore matter when choosing a place to unload. Ask the person at the Cardiff property for clear street photos, including the proposed stopping point. Where access requires permission, settle it in advance rather than assuming a furniture delivery can stop anywhere near the door.", source: sources.cardiff },
      { title: "Measure the Cardiff entrance before wrapping bulky pieces", body: "Check the gate, front path, porch and internal turns at the new property against the dimensions of your Glasgow sofa, mattress and wardrobe. If a rear entrance is proposed, confirm permission and whether the full route is clear. Send the measurements before booking so the handling plan does not depend on removing doors or using neighbouring land without agreement." },
      { title: "Set up an arrival contact who can make decisions", body: "Give the Cardiff recipient a copy of the inventory and the intended room for large items. Explain what should happen if a piece will not fit through its intended doorway and who can authorise a different position. Keep first-night essentials apart from the main load, especially if you are travelling separately and may reach the property at a different time." },
    ],
    faqs: [
      { question: "Do you move items from Glasgow to Wales?", answer: "Yes, this route starts with collection in Scotland and ends in Cardiff. Provide the full collection and delivery addresses, items and dates so the practical access and transport requirements can be assessed." },
      { question: "Can the van use the resident bay outside my Cardiff home?", answer: "Check the actual bay restrictions and the planned activity with the relevant authority. Send the sign details before booking. A space being empty does not by itself establish that the vehicle can use it for the whole move." },
      { question: "What if the Cardiff entrance is smaller than my Glasgow entrance?", answer: "Measure the narrowest opening and turns, and send the furniture dimensions. Discuss dismantling or another approved access route before the move rather than waiting until the item has reached the destination." },
    ],
  },
  {
    slug: "glasgow-to-edinburgh",
    originSlug: "glasgow",
    destination: "Edinburgh",
    title: "Glasgow to Edinburgh moving service",
    description: "Organise Glasgow to Edinburgh removals around two-city access, shared stairs, parking arrangements and a clear loading and unloading sequence.",
    introduction: "A move between Glasgow and Edinburgh can still have complicated property access at both ends. Two upper-floor flats, a delayed tenancy handover or a time-limited loading space may shape the job more than the city-to-city journey. Describe the two buildings separately when requesting your move.",
    sections: [
      { title: "Check both city-centre approaches", body: "Glasgow and Edinburgh each have a city-centre LEZ. Give the precise entrances at both addresses so the vehicle approach can be checked at each end. Add the floor and any stairs between street level and the front door; a map pin outside the building does not show a shared close, basement steps or the route through a rear courtyard.", source: sources.scottishLez },
      { title: "Arrange Edinburgh loading before choosing an arrival window", body: "Edinburgh offers separate dispensation and bay-suspension arrangements. Ask which is relevant to the destination street and how much notice the current application needs. Coordinate the approved location with the actual flat entrance. If the vehicle must unload farther away, tell us before confirming the move so the carrying route and handling requirement can be considered.", source: sources.edinburgh },
      { title: "Compare both staircases for your largest pieces", body: "For a tenement-to-tenement move, measure the difficult turn in Glasgow and the difficult turn in Edinburgh. A wardrobe that exits one flat intact may need dismantling to enter the other. Photograph the landings, ceiling clearance and doorways, then agree which pieces will be prepared before collection. Keep shared corridors usable throughout the process." },
      { title: "Build the day around two property handovers", body: "Write down when you must return the Glasgow keys, when the Edinburgh keys will actually be available and whether either building restricts moving hours. Keep the people handling each address reachable. If your own travel arrangements leave the destination empty, nominate someone who can receive the inventory and direct the furniture rather than asking the driver to wait for access." },
    ],
    faqs: [
      { question: "Does a shorter intercity move need the same access information?", answer: "Yes. Stairs, furniture dimensions and loading space affect the handling regardless of the distance. Provide separate access notes for the Glasgow collection and Edinburgh delivery." },
      { question: "Can I use my Edinburgh resident permit for the removal van?", answer: "Do not assume it covers the planned vehicle and activity. Check the destination bay and the council's removal-related parking options before the move, then share any approval and its conditions." },
      { question: "Can the team collect and then wait until I receive the new keys?", answer: "Explain the gap between the two handovers in your request. Any waiting or alternative arrangement must be agreed in advance; a route guide does not establish an included waiting period." },
    ],
  },
  {
    slug: "edinburgh-to-london",
    originSlug: "edinburgh",
    destination: "London",
    title: "Edinburgh to London removals",
    description: "Plan an Edinburgh to London move with collection parking, London red-route checks, packing preparation and coordinated building access.",
    introduction: "Leaving Edinburgh for London involves a collection address with its own access rules and a destination that may have a different road authority. Start the plan early enough to deal with both. Give us the property entrances and any fixed key or concierge appointments, alongside the items being moved.",
    sections: [
      { title: "Resolve Edinburgh collection parking before packing day", body: "Edinburgh's dispensation and suspension options address different parking situations. Work out the suitable collection location while planning the move, and check the application notice requirements with the council. Photograph the route from your flat or house to that location. If an upper-floor property needs extended handling, explain that before settling on a loading window.", source: sources.edinburgh },
      { title: "Get a London unloading position with a usable carrying route", body: "For a London red-route address, TfL says goods should be ready when a loading bay is used. Ask the recipient to confirm the entrance, access code and available lift beforehand. Record the bay sign and any suspension notice, then check whether that position can support the move. Borough roads require the relevant borough's own parking arrangements.", source: sources.london },
      { title: "Pack an Edinburgh departure box and a London arrival box", body: "Keep cleaning materials and tenancy paperwork available until you finish the Edinburgh handover, then separate bedding, chargers and essentials for arrival in London. Label the main load by destination room instead of only by its old room. For a smaller London property, compare the furniture list with the new room measurements before paying to transport pieces you cannot place." },
      { title: "Confirm who has authority at the delivery building", body: "A letting agent, concierge and tenant may each control different parts of the London arrival. Establish who holds the keys, who opens the service entrance and who receives the contents. Put these contacts in the move notes before collection. Advise us if access is conditional on a lift booking or building induction so delivery can be arranged around the real requirements." },
    ],
    faqs: [
      { question: "How early should I check parking for an Edinburgh to London move?", answer: "Check both addresses while choosing your moving date. Councils and building managers may require advance notice, so review their current application details before treating a proposed collection or delivery window as settled." },
      { question: "Can I send boxes to a London flat before I arrive?", answer: "Provide an authorised recipient who can access the correct flat and receive the items. A concierge accepting parcels does not necessarily mean the building will accept a household removal without the resident present." },
      { question: "Do I need to list every item for a small move?", answer: "Give a clear box count plus each furniture or bulky item, including dimensions where access may be tight. Mention items in Edinburgh storage spaces and any additional collection point so the transport request is complete." },
    ],
  },
  {
    slug: "edinburgh-to-manchester",
    originSlug: "edinburgh",
    destination: "Manchester",
    title: "Edinburgh to Manchester moving service",
    description: "Prepare an Edinburgh to Manchester house or flat move with accurate access notes, loading-bay checks, lift details and a labelled inventory.",
    introduction: "For Edinburgh to Manchester moves, a useful quote starts with what must leave the Edinburgh property and how it will enter the new one. Include the access details for each address rather than assuming the two flats have similar stairs, parking or lift arrangements.",
    sections: [
      { title: "Plan the Edinburgh collection around the actual street space", body: "Ask whether the proposed collection point needs an Edinburgh parking dispensation or a bay suspension, and check the current notice requirements. If you live above ground level, include the stair flights and whether there is room to turn large items on landings. Prepare the inventory before requesting parking arrangements so the proposed loading activity matches the move.", source: sources.edinburgh },
      { title: "Match Manchester loading rules to the receiving entrance", body: "Manchester loading bays may have vehicle restrictions as well as activity restrictions. Obtain the sign details for the intended stop and ask whether the building uses a rear goods entrance. A public bay on the front street can be unhelpful if furniture must enter from another road. Confirm the approved route through any shared car park or courtyard.", source: sources.manchester },
      { title: "Treat a change in home size as an inventory decision", body: "If you are moving from a furnished Edinburgh tenancy into an unfurnished Manchester home, distinguish the landlord's items from your own before collection. Conversely, check which large pieces the new property already contains. Label only the items travelling and keep any disposal or sale arrangement separate from the move so the team has a clear list to collect." },
      { title: "Make the receiving apartment ready for the first items", body: "Ask for the Manchester lift opening size and any protective lining or reservation requirements. Mark furniture intended for the room farthest from the entrance so the unloading order can be discussed. Keep door keys and fobs with the receiving person; putting them in a labelled box still makes them inaccessible while the van is being unloaded." },
    ],
    faqs: [
      { question: "Can I move only my own furniture from a furnished Edinburgh flat?", answer: "Yes, identify the items travelling and make it clear which landlord-owned pieces must stay. Use labels or a written list, and include the contents of cupboards only if they are part of your move." },
      { question: "What Manchester lift information is useful?", answer: "Provide the door opening and internal dimensions, booking rules, floor number and the distance from the legal unloading point. If the lift cannot take a piece, the alternative handling must be assessed beforehand." },
      { question: "Can someone else receive my Edinburgh belongings?", answer: "Give the authorised recipient the inventory, room instructions and the access arrangements. Share their contact details when planning the job so arrival does not depend on finding you at the Edinburgh property." },
    ],
  },
  {
    slug: "edinburgh-to-newcastle",
    originSlug: "edinburgh",
    destination: "Newcastle upon Tyne",
    title: "Edinburgh to Newcastle removals",
    description: "Plan Edinburgh to Newcastle upon Tyne removals with collection access, destination dispensation checks, inventory and key-handover details.",
    introduction: "This guide covers moves collected in Edinburgh and delivered to Newcastle upon Tyne. Confirm the destination postcode at the start, then plan the street access and handover at both properties. A modest load still needs the right stopping place and someone ready to receive it.",
    sections: [
      { title: "Prepare the Edinburgh exit route before confirming collection", body: "Record the number of stair flights, narrow entrance turns and the distance to the intended vehicle position. Edinburgh offers removal-related parking arrangements, but the correct application depends on the street. Check that early and tell us about its approved location and times. Stage packed items inside the property without filling the shared escape route.", source: sources.edinburgh },
      { title: "Check whether Newcastle needs a parking dispensation", body: "Newcastle's council considers dispensations for furniture deliveries and removals, with conditions and advance application requirements. Ask about the exact delivery location instead of treating a dispensation as automatic. If a suitable ordinary loading space is available, record it along with the path to the entrance. Include pedestrian-only access or restricted vehicle entry in the delivery notes.", source: sources.newcastle },
      { title: "Keep a compact move accurately described", body: "For an Edinburgh flatshare or student departure, count boxes once packing is nearly complete and measure bulky extras such as bikes, desks and bed frames. Say which items belong to you if the Edinburgh property remains occupied. At Newcastle, identify the bedroom or floor and who will keep the shared entrance clear while the items arrive." },
      { title: "Coordinate two tenancies without relying on a driving estimate", body: "Record the checkout deadline in Edinburgh and the earliest confirmed access to the Newcastle property. Allow the plan to reflect loading, travel and unloading, not just a navigation estimate. If you will be travelling independently, give an alternative receiving contact and explain any access appointments before the move is booked." },
    ],
    faqs: [
      { question: "Which Newcastle does this route cover?", answer: "The destination is Newcastle upon Tyne. Enter the full delivery postcode and address so there is no confusion with another place using the Newcastle name." },
      { question: "Is a Newcastle parking dispensation guaranteed for removals?", answer: "No. The council assesses requests against its conditions. Check the current guidance and the actual street arrangements, then share any approval before relying on the proposed unloading location." },
      { question: "Can I add a bicycle to a box-only Edinburgh move?", answer: "Include it in the inventory before confirming the booking, with its dimensions and any packing needs. An extra bulky item can change the space and handling needed even when the box count is unchanged." },
    ],
  },
  {
    slug: "edinburgh-to-bristol",
    originSlug: "edinburgh",
    destination: "Bristol",
    title: "Edinburgh to Bristol removals",
    description: "Organise an Edinburgh to Bristol move with parking preparation, Bristol Clean Air Zone checks, property measurements and an arrival plan.",
    introduction: "An Edinburgh to Bristol move needs a plan for the furniture, the collection street and the final delivery entrance. Give us the full addresses and the move inventory first. Then add the building access and key arrangements that could constrain when the collection or unload can happen.",
    sections: [
      { title: "Set up the Edinburgh loading arrangement with enough notice", body: "Identify whether the vehicle can load from a suitable space or whether a council parking arrangement is needed. Edinburgh's guidance separates dispensations from suspensions, so check the option appropriate to the street. If collecting from a flat, send the stair and doorway photographs with the inventory rather than discovering difficult furniture turns after the parking window starts.", source: sources.edinburgh },
      { title: "Check the Bristol address and assigned vehicle", body: "Bristol links to the official vehicle checker for its Clean Air Zone. Use the actual vehicle registration when the transport is arranged and check how the destination will be approached. Tell us about any separate rear service entrance, since the postal address and vehicle entrance may differ. Zone compliance does not determine whether a stopping position is suitable for unloading.", source: sources.bristol },
      { title: "Measure changes of level at the Bristol property", body: "Ask the recipient for photographs from the pavement to the front door, including steps, gates and any sloping path. Compare the narrowest point with furniture leaving Edinburgh. If delivery is to an upper floor, check every turn from the entrance to that floor; the front door width alone cannot show whether a rigid table or tall cabinet will fit." },
      { title: "Prepare for separate personal travel and goods handover", body: "Keep travel documents, medication, chargers and property keys out of the furniture load. Name the person meeting the delivery in Bristol and give them a room plan. If you are completing an Edinburgh tenancy inspection before travelling, arrange how the receiving person will hear about any schedule change so the Bristol entrance remains accessible when needed." },
    ],
    faqs: [
      { question: "Will the Bristol Clean Air Zone affect my move?", answer: "That depends on the destination, approach and assigned vehicle. Check the current official guidance and vehicle checker when organising the job; the route name alone cannot establish whether a charge applies." },
      { question: "What if my Bristol home has steps outside?", answer: "Include their number and photographs, along with the path width and the large items to be delivered. External steps need to be considered even if the receiving rooms are all on the ground floor." },
      { question: "Can I give a preferred Bristol arrival appointment?", answer: "Yes, include it in the request together with the Edinburgh collection constraints. The two windows need to be assessed together before a delivery schedule can be agreed." },
    ],
  },
  {
    slug: "aberdeen-to-london",
    originSlug: "aberdeen",
    destination: "London",
    title: "Aberdeen to London removals",
    description: "Prepare Aberdeen to London removals with collection-zone checks, a complete inventory, London loading access and a named delivery contact.",
    introduction: "Before moving from Aberdeen to London, confirm the entire load and the person who can open the destination property. Correcting an omitted item or an unavailable entrance after departure is difficult on an intercity move. Build the request around the real collection and delivery conditions.",
    sections: [
      { title: "Confirm the collection entrance in Aberdeen", body: "Aberdeen has a city-centre LEZ. Give the actual street entrance and collection postcode so the vehicle approach can be assessed. For a property with front and rear access, explain which entrance can legally and practically be used. Include stair flights and narrow passages between rooms, not just the outdoor loading distance, when describing the collection.", source: sources.scottishLez },
      { title: "Make the London unload possible before leaving Aberdeen", body: "TfL's red-route guidance requires attention to the individual loading-bay signs. Ask the London contact to send the proposed stopping location and the route from it to the correct entrance. Where the address is on a borough road, consult that authority instead. Confirm keys and any lift access before relying on a particular delivery window.", source: sources.london },
      { title: "Audit cupboards, sheds and separate storage before loading", body: "Walk through the Aberdeen property after making the inventory and check any outbuilding or storage space included in the move. List garden tools, folded furniture and loose items that are easily overlooked. Tell us about items needing preparation or unsuitable for ordinary transport, and agree the contents to be carried before the loading plan is settled." },
      { title: "Document who receives valuable or fragile items", body: "Identify delicate furniture and boxed equipment in the Aberdeen inventory, with photographs and any preparation instructions. Give the London recipient the same list so the handover can be checked against it. Keep small valuables and essential personal documents with you, and explain any building deadline that could affect bringing the remaining load indoors." },
    ],
    faqs: [
      { question: "Can my Aberdeen move include items in a separate store?", answer: "Declare the additional collection address, access hours and contents before booking. It is a separate stop to plan, even if the storage unit is close to the home." },
      { question: "Should I book a London bay before requesting the move?", answer: "First establish which authority and arrangement apply, then coordinate the date, duration and vehicle details. The parking approval and the transport schedule need to agree before either is treated as final." },
      { question: "Is the Aberdeen to London delivery time fixed?", answer: "No fixed transit time is promised on this page. Provide the date, inventory and access constraints so collection and delivery can be arranged for the actual job." },
    ],
  },
  {
    slug: "aberdeen-to-edinburgh",
    originSlug: "aberdeen",
    destination: "Edinburgh",
    title: "Aberdeen to Edinburgh moving service",
    description: "Plan an Aberdeen to Edinburgh move around collection access, Edinburgh loading arrangements, furniture dimensions and property handovers.",
    introduction: "For Aberdeen to Edinburgh removals, plan how the same furniture will pass through two different properties. An easy collection does not guarantee an easy delivery into an Edinburgh flat. Include photos, floor information and the destination loading position in the request from the start.",
    sections: [
      { title: "Assess the Aberdeen address and vehicle approach", body: "Check the Aberdeen collection against the city-centre LEZ and identify the actual loading entrance. Let us know if the property is reached through a shared hall or a rear lane rather than directly from the street. Mark which large items are already dismantled and which would need assessment before they can leave the home.", source: sources.scottishLez },
      { title: "Arrange an Edinburgh stopping point that reaches the flat", body: "Edinburgh's parking guidance provides dispensation and suspension options. Check the relevant arrangement for your destination and its current notice period. Photograph the carrying route from the proposed position to the Edinburgh entrance. If the route involves steps or a courtyard, include them when describing delivery rather than counting only the stairs inside the building.", source: sources.edinburgh },
      { title: "Check furniture against Edinburgh stair turns", body: "Compare the dimensions of long Aberdeen items with the narrowest Edinburgh landing and doorway. A bed frame can often be planned as separate components, while a solid cabinet needs a different assessment. Send photographs showing the full turn and ceiling above it. Agree any dismantling requirement before wrapping the furniture and keep the components together." },
      { title: "Plan the handover around the new home's readiness", body: "Ask whether the Edinburgh property will be empty, cleaned and accessible when the contents arrive. If other work is taking place, identify a clear route and rooms where furniture may be placed. Coordinate that with the Aberdeen checkout deadline and name a recipient who can direct the unload while keeping shared building access clear." },
    ],
    faqs: [
      { question: "Do both Aberdeen and Edinburgh need vehicle-access checks?", answer: "Yes. Check each exact address and approach, and separately confirm suitable loading and unloading positions. A vehicle-access check for one city does not describe the property access at the other." },
      { question: "What is useful when delivering to an Edinburgh tenement?", answer: "The floor number, stair flights, narrow turns, door widths and distance from the unloading point. Clear photos and the dimensions of the largest items help assess the handling before collection in Aberdeen." },
      { question: "Can furniture arrive while work is still happening in the new flat?", answer: "Explain the work, access restrictions and which rooms are available before booking. The destination needs a safe receiving route and an agreed place for the contents; do not assume the shared stair can be used as storage." },
    ],
  },
  {
    slug: "aberdeen-to-manchester",
    originSlug: "aberdeen",
    destination: "Manchester",
    title: "Aberdeen to Manchester removals",
    description: "Arrange an Aberdeen to Manchester move with a checked inventory, collection access, Manchester loading details and building-manager coordination.",
    introduction: "An Aberdeen to Manchester move may combine a full household collection with tightly managed apartment delivery. Give us a complete list of items and the destination access requirements before the moving date. That allows the collection plan to reflect what can actually be carried into the Manchester property.",
    sections: [
      { title: "Describe the complete Aberdeen collection", body: "Provide the collection postcode, floor and photographs of the entrance and loading approach. Aberdeen's central LEZ needs a vehicle check where the route enters it. Also distinguish items in the home from items in a garage or separate store. If there is more than one collection point, list each one with its own access contact and opening constraints.", source: sources.scottishLez },
      { title: "Clarify Manchester's public bay and private building rules", body: "Manchester's loading-bay guidance covers permitted activity and vehicle restrictions, while a private building may have a separate booking process. Check both. Ask whether the managing agent needs a vehicle registration, service entrance appointment or lift reservation. Share these requirements with the move request rather than assuming an ordinary visitor parking space will work for the unloading.", source: sources.manchester },
      { title: "Measure what moves between very different layouts", body: "If a large Aberdeen house is becoming a Manchester flat, compare the planned furniture list with the new floor plan before collection. Measure the lift, internal doors and corners needed to reach each room. Separate items being sold or left behind so the team receives an unambiguous loading list, particularly if several people are helping pack." },
      { title: "Give the move one agreed communication chain", body: "Nominate a collection contact in Aberdeen and a delivery contact in Manchester, and explain who can authorise changes to item placement or access. Give both people the same inventory and preferred room labels. Confirm the route for updates if you will be travelling separately, so a changed key time reaches the receiving person before the vehicle arrives." },
    ],
    faqs: [
      { question: "Can the move include a home office from Aberdeen?", answer: "Include the desks, chairs, screens and boxed equipment in the inventory and flag any specialist preparation. Describe the Manchester receiving rooms and lift limits so office items can be considered alongside the household load." },
      { question: "What if the Manchester managing agent needs vehicle details?", answer: "Tell us what information and notice the building requires before booking. Vehicle allocation and any registration-dependent permission must be coordinated with the agreed moving arrangement." },
      { question: "Can I change the load after receiving a quote?", answer: "Report additional or removed items before the move is confirmed or as soon as the change is known. More furniture or an extra Aberdeen stop can alter the transport and handling requirements." },
    ],
  },
  {
    slug: "inverness-to-glasgow",
    originSlug: "inverness",
    destination: "Glasgow",
    title: "Inverness to Glasgow removals",
    description: "Prepare an Inverness to Glasgow move with practical collection parking, current travel checks, Glasgow entry access and a furniture handover plan.",
    introduction: "For Inverness to Glasgow moves, start with a collection location that can support the loading and an arrival address that can receive the whole load. A city-centre collection, a house driveway and an upper-floor Glasgow flat each need different information. Include the details for your actual properties.",
    sections: [
      { title: "Check the Inverness collection space, not only the postcode", body: "Highland Council lists Church Street parking as time-limited pay-and-display space. If that is near your collection, do not treat an ordinary bay as a pre-arranged removal position. Check the relevant street signs and explain the carrying route from the entrance. At a private driveway, include the gate width, turning space and any overhead obstruction instead.", source: sources.inverness },
      { title: "Use current road information when agreeing the journey", body: "Review Traffic Scotland's live travel information while finalising the Inverness departure and again close to the move. Tell us about a fixed Glasgow key appointment or building access deadline so the transport plan can account for it. A navigation estimate alone leaves out loading, breaks, disruption and the time needed to bring furniture into the destination.", source: sources.trafficScotland },
      { title: "Prepare for the Glasgow building rather than just the journey", body: "A central Glasgow address may require an LEZ check. Also record the floor, close entrance and difficult stair turn at the destination. Measure the largest Inverness pieces against that route before wrapping them. Where a lift is available, check its usable dimensions and whether the building requires a moving appointment; its presence does not establish that every item will fit.", source: sources.scottishLez },
      { title: "Leave the right items accessible at each handover", body: "Keep Inverness checkout paperwork and house keys separate from the load, and create a clearly labelled box of Glasgow essentials. Tell the receiving contact which furniture belongs in each room. If you are not travelling with the goods, share their phone number and explain who can answer questions about access or placement during the unload." },
    ],
    faqs: [
      { question: "What access details matter for Inverness collection?", answer: "The street or driveway position, the path to the door, any stairs and the sizes of bulky furniture. If the loading point is a public bay, include its sign details and any parking arrangement being made." },
      { question: "Can I choose a Glasgow delivery window?", answer: "Provide your preferred window and any fixed property access deadline. It needs to be assessed with the Inverness collection and the whole move before an arrival arrangement is confirmed." },
      { question: "Will a Glasgow lift make the move simpler?", answer: "It may help, but give its internal and door dimensions, booking requirements and the route from the van. Furniture that cannot use it needs a separately assessed handling plan." },
    ],
  },
  {
    slug: "inverness-to-edinburgh",
    originSlug: "inverness",
    destination: "Edinburgh",
    title: "Inverness to Edinburgh moving service",
    description: "Plan Inverness to Edinburgh removals around trunk-road conditions, destination loading approval, tenement access and the timing of key handovers.",
    introduction: "An Inverness to Edinburgh move should connect a prepared collection with a usable unloading window. The Edinburgh building may need parking arrangements or a booked lift before furniture can arrive. Gather those details while preparing the Inverness inventory so neither end is planned in isolation.",
    sections: [
      { title: "Make Inverness collection access explicit", body: "Photograph where the van would stop and the route from the Inverness entrance. Church Street's council-listed parking has a maximum stay, so a central bay should be checked against the proposed loading activity. For addresses away from that street, inspect the actual restrictions or private access instead of applying one city-centre example to the whole city.", source: sources.inverness },
      { title: "Plan the travel leg with current information", body: "Traffic Scotland publishes incidents, works and travel warnings. Review the relevant route when agreeing the move, then reconfirm conditions near departure. Keep the Edinburgh contact informed if access is tied to a booked facility. This is especially useful where the building offers a limited receiving window that cannot simply be shifted after leaving Inverness.", source: sources.trafficScotland },
      { title: "Match Edinburgh parking permission to the flat entrance", body: "Edinburgh has separate procedures for a parking dispensation and a bay suspension. Check which one suits the destination, and ensure any approved space is connected to the correct entrance by a workable carrying route. Describe external steps and communal stairs separately. If a rear entrance is proposed, confirm that the property manager permits its use for the move.", source: sources.edinburgh },
      { title: "Plan furniture assembly around the receiving rooms", body: "For a move into an Edinburgh flat, decide which Inverness items need dismantling to pass the final stair turn. Label the parts by room and keep fixings with the correct piece. Explain any assembly help needed in the original request, and keep the receiving rooms clear so furniture is not stacked in a shared corridor while positions are decided." },
    ],
    faqs: [
      { question: "Should I arrange Edinburgh parking before the Inverness collection?", answer: "Resolve the destination requirements during planning, then coordinate any approval with the transport date and vehicle details. Check current council notice requirements before relying on a particular unloading window." },
      { question: "Can the collection be from an Inverness storage unit?", answer: "Provide the exact unit address, access hours, unit location, lift information and inventory. Tell us whether loading needs a booked bay or a code, and who will be present to release the contents." },
      { question: "How do I describe difficult Edinburgh stairs?", answer: "Send photographs of the entrance, landings and tight turns with the floor number and large-item measurements. Include ceiling clearance and any handrail that narrows the usable route." },
    ],
  },
  {
    slug: "inverness-to-london",
    originSlug: "inverness",
    destination: "London",
    title: "Inverness to London removals",
    description: "Prepare a long-distance move from Inverness to London with a complete inventory, current journey checks and workable destination loading access.",
    introduction: "For Inverness to London removals, preparation at both addresses is essential to a workable booking. Confirm the whole load, any restricted collection access and who can admit the team in London. This guide focuses on those decisions without assuming a fixed journey time or delivery slot.",
    sections: [
      { title: "Complete the Inverness inventory before the vehicle plan", body: "Count packed boxes and list large furniture, outdoor items and anything in a separate store. Photograph the collection approach and identify where loading can take place for the expected activity. If you propose a central Inverness parking bay, check its actual restrictions; Highland Council's Church Street listing, for example, is time limited rather than an unrestricted loading allocation.", source: sources.inverness },
      { title: "Keep journey planning separate from a promised arrival", body: "Use current Traffic Scotland information when planning departure from Inverness, and provide any London access deadline before the schedule is agreed. Collection handling and the receiving building are part of the move as well as road travel. Keep a contact available at each property so a changed key time or access issue can be addressed before it blocks the handover.", source: sources.trafficScotland },
      { title: "Make the London loading arrangement specific", body: "TfL red-route bays have individual signs governing use. Identify whether the destination is on that network, obtain the proposed bay details and ask whether a dispensation or other arrangement is appropriate. If the road belongs to a borough, use its guidance. Confirm the walking route into the property and any lift appointment at the same time.", source: sources.london },
      { title: "Prepare the recipient for a complete household arrival", body: "Give the London recipient a room-labelled inventory and instructions for furniture that was dismantled in Inverness. Keep essentials, keys and personal paperwork with you. If some items are going to another London address, state that stop before booking so loading order, access contacts and the delivery arrangement cover both destinations." },
    ],
    faqs: [
      { question: "Can you promise a set Inverness to London travel time?", answer: "This page does not promise a fixed transit time. The agreed arrangement must consider the load, handling, road conditions and access at both properties." },
      { question: "What if I need a second London delivery address?", answer: "Add it to the request before booking, with its own items, entrance, floor and receiving contact. It changes the job's scope and should be included in the loading and delivery plan." },
      { question: "Can London furniture access be checked while I am still in Inverness?", answer: "Ask the agent, landlord or recipient for measurements and photographs of the entrance, lift and stairs. Share them with the large-item dimensions before the move is confirmed." },
    ],
  },
  {
    slug: "dundee-to-london",
    originSlug: "dundee",
    destination: "London",
    title: "Dundee to London removals",
    description: "Plan Dundee to London furniture and household moves with Dundee zone checks, London unloading access and a clear packing and handover sequence.",
    introduction: "A Dundee to London move needs more detail than the two postcodes. The collection could be a flat, a house or a storage unit, while the London destination may require a managed delivery appointment. Describe the items and access at both ends so the job can be assessed accurately.",
    sections: [
      { title: "Locate the Dundee collection against the LEZ map", body: "Dundee's council provides an LEZ map covering an area within the A991 Inner Ring Road, with specified exclusions. Check the actual collection entrance and vehicle approach against that map rather than relying on a broad city-centre label. Also identify the legal loading position, carrying distance and floor, since entering the area and loading at the property are separate requirements.", source: sources.dundee },
      { title: "Confirm London's road and building access together", body: "Where the destination uses a TfL red-route loading bay, check its signs and availability before settling on the unload. Ask the recipient for the service entrance, lift arrangements and a contact who can open the building. If those arrangements require advance booking, share the requirements while organising collection in Dundee rather than after the load is on its way.", source: sources.london },
      { title: "Separate belongings from furniture that stays in Dundee", body: "For a furnished tenancy, make a clear list of your possessions and mark any landlord furniture that must remain. Include bikes, musical equipment or a desk separately from the box count, with dimensions and protection requirements. Take a final walk through the property before handover so the agreed load does not omit cupboards or storage areas." },
      { title: "Plan room placement for the new London layout", body: "Check that larger pieces have both a usable entry route and a planned position inside the new property. A piece fitting through the front door does not prove it will turn into a bedroom. Label boxes by London room and give the receiver the same inventory used in Dundee, including a note of parts belonging to dismantled furniture." },
    ],
    faqs: [
      { question: "Does the Dundee LEZ cover every Dundee address?", answer: "No. Use the council's boundary information and the exact collection entrance. The vehicle approach also matters, so do not infer zone access only from the destination of a map pin." },
      { question: "Can a Dundee student move include furniture?", answer: "List the furniture, boxes and bulky equipment you own, and distinguish them from landlord items. Give the London floor and lift details so the whole load can be considered together." },
      { question: "What should the London receiver have ready?", answer: "Access to the correct property, any required fob or lift booking, the room-labelled inventory and a working phone. Tell us beforehand if the receiver must leave by a fixed time." },
    ],
  },
  {
    slug: "perth-to-manchester",
    originSlug: "perth",
    destination: "Manchester",
    title: "Perth to Manchester removals",
    description: "Plan a move from Perth, Scotland to Manchester with pedestrian-zone checks, suitable unloading space, furniture measurements and clear handovers.",
    introduction: "This route starts in Perth, Scotland and delivers to Manchester. Share the full collection address and whether it is in the centre, reached by a private drive or accessed through shared premises. Match that information with the destination loading and building details before choosing a move arrangement.",
    sections: [
      { title: "Check Perth pedestrian-zone access separately", body: "Perth and Kinross Council distinguishes applications inside Perth's pedestrian zone from dispensations elsewhere. Check the process relevant to the collection street before assuming an ordinary parking request covers it. Give the actual building entrance and proposed loading position, and confirm any permissions needed from a private site or property manager as a separate part of preparation.", source: sources.perth },
      { title: "Identify a Manchester bay that suits the load", body: "Manchester's council notes that some loading bays are limited to commercial vehicles. Check the intended bay's sign and ask the recipient how to reach the property from it. If the unload is into a private development, find out whether a separate bay or entrance must be booked. Include the carrying distance rather than simply reporting that parking exists nearby.", source: sources.manchester },
      { title: "Compare a Perth house inventory with a Manchester flat", body: "If you are changing property size, decide what travels before finalising the quote. Measure wardrobes, dining tables and garden furniture against the new property's access and rooms. Explain whether dismantling is required at Perth and assembly is wanted in Manchester; those are handling tasks to agree, not details that can safely be inferred from a room count." },
      { title: "Align collection release with destination access", body: "Name someone who can release all listed items at the Perth property and someone who can receive them in Manchester. If an agent or concierge controls the destination, obtain their access procedure and any deadline. Keep both contacts informed of the agreed plan and flag possible changes before the move rather than relying on the recipient to solve access on arrival." },
    ],
    faqs: [
      { question: "Is this Perth in Scotland?", answer: "Yes. Enter the full Scottish collection postcode and the Manchester delivery address when requesting the move, together with the items and access details." },
      { question: "Can a collection take place in Perth's pedestrian zone?", answer: "The exact access and parking requirements must be checked first. Consult the council's current process for that location and provide any applicable permission, access times and entrance details." },
      { question: "What if Manchester delivery is into a managed development?", answer: "Ask about service-bay bookings, barriers, lift dimensions and permitted delivery times. Provide the building contact and requirements before the date is confirmed." },
    ],
  },
  {
    slug: "stirling-to-birmingham",
    originSlug: "stirling",
    destination: "Birmingham",
    title: "Stirling to Birmingham removals",
    description: "Prepare Stirling to Birmingham removals with collection parking, Birmingham Clean Air Zone checks, furniture access and coordinated property handovers.",
    introduction: "A Stirling to Birmingham move should account for the collection street as carefully as the destination. Send photos showing the route between the Stirling entrance and the loading position, then add the Birmingham building's access instructions. These details make the inventory useful for practical planning.",
    sections: [
      { title: "Do not rely on a Stirling resident permit to reserve loading", body: "Stirling Council explains that a resident permit does not guarantee a space or authorise use of every restricted bay. Check the proposed collection position and any arrangement needed for the moving vehicle. If the property has steps or a sloping path, photograph the full route and describe where furniture can be handled without obstructing other residents.", source: sources.stirling },
      { title: "Check the Birmingham address before allocating the vehicle", body: "The Birmingham Clean Air Zone covers the area inside the A4540 Middleway, not the Middleway itself. Use the destination and entrance details to check the approach and the assigned vehicle's status. If the building has a separate service road, include that address too. Confirm the unloading space independently of the emissions-zone check.", source: sources.birmingham },
      { title: "Plan rigid furniture around both entrances", body: "Measure long pieces leaving Stirling and the turns they will need to make at the Birmingham property. Note whether a table separates into parts and whether appliances have been prepared for movement. Tell us which preparation or assembly tasks you want assessed before booking; do not assume they are covered simply because an item appears in the inventory." },
      { title: "Give an accurate handover sequence for a house purchase", body: "Write down the Stirling key-return requirement and the Birmingham key-release arrangement, including who will confirm each. If the receiving property is part of a chain, describe any uncertainty before the transport is agreed. Keep essential belongings with you and nominate a receiving contact who can direct the load into the correct rooms once access is available." },
    ],
    faqs: [
      { question: "Does my Stirling parking permit reserve space for the van?", answer: "Do not rely on it to reserve a loading position. Check the exact street and vehicle requirements with the council or site manager, and tell us the intended loading arrangement." },
      { question: "Can you deliver to a Birmingham city-centre apartment?", answer: "Provide the postcode, service entrance, floor, lift dimensions and any appointment requirements. The vehicle and building access need to be checked against that address before the move is confirmed." },
      { question: "How should I describe uncertain Birmingham key release?", answer: "Explain the expected date, who releases the keys and what remains unconfirmed. Agree how the move would handle a changed handover before booking; do not build the plan around an unconfirmed arrival time." },
    ],
  },
  {
    slug: "dunfermline-to-newcastle",
    originSlug: "dunfermline",
    destination: "Newcastle upon Tyne",
    title: "Dunfermline to Newcastle removals",
    description: "Plan Dunfermline to Newcastle upon Tyne removals with collection-road checks, Newcastle unloading requirements and an accurate item and access list.",
    introduction: "For a move from Dunfermline to Newcastle upon Tyne, use the full addresses to establish collection and delivery access. Explain whether the load comes from a house, upper-floor flat or storage unit, and whether the receiving property has a restricted unloading position or key appointment.",
    sections: [
      { title: "Check the Dunfermline collection approach near moving day", body: "Fife Council provides roadworks and maintenance information for local roads. Review the approach to the collection property and any relevant changes while planning the move. Send photographs of the intended loading position, entrance and carrying route. If access is through private premises or a controlled entry, identify who can authorise and open it for the moving vehicle.", source: sources.fife },
      { title: "Resolve Newcastle unloading permissions in advance", body: "Newcastle City Council's dispensation process includes furniture removals, subject to its conditions and notice requirements. Check the intended delivery location before relying on such permission. If the ordinary loading arrangement is suitable, record the sign and carrying route instead. For a building with its own service bay, also obtain the manager's booking and access instructions.", source: sources.newcastle },
      { title: "Keep small loads detailed enough to assess", body: "A Dunfermline flatshare move might have few large items but many boxes, bikes or work supplies. Count them and identify awkward pieces individually rather than describing the job only as a small move. At Newcastle, check the destination floor and room access, and tell us whether another resident will receive the load on your behalf." },
      { title: "Prepare a two-address handover checklist", body: "Confirm the Dunfermline collection contact, the Newcastle receiving contact, the items travelling and the room labels. If you must return the old keys before obtaining the new ones, explain the gap while requesting the move. Keep documents and essential belongings outside the main load, and make sure the recipient can open all doors needed to bring the furniture inside." },
    ],
    faqs: [
      { question: "Does this route end in Newcastle upon Tyne?", answer: "Yes. Enter the full delivery postcode to identify the correct property and local authority, especially if the address is outside Newcastle City Council's boundary." },
      { question: "Can someone else handle the Dunfermline collection?", answer: "Provide an authorised contact who can open the property, identify the agreed items and answer access questions. Give that person the same inventory used for the booking." },
      { question: "How do I plan a Newcastle flat delivery without being there?", answer: "Arrange an authorised receiver with the keys, room instructions and any lift or service-bay booking. Give their contact details in advance and confirm that the building allows the proposed arrangement." },
    ],
  },
];
